### ISSUE TITLE
Room Behavior (pluggable behaviors)

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#1046]
This is a summary of an idea that was discussed yesterday in Discord exposed here for everyone to weigh in.

## Problem

Certain rooms will have need of coordination and functionality beyond just being a room, but we don't want to embed that functionality in either of the furniture that goes into it. The best example we have right now is an Airlock. An airlock needs at a minimum an Airlock Door and an Air Pump, but might have several of them. It's unclear exactly which of them are in charge.

## Solution

We create a new interface `IRoomBehavior` that looks something like this:

```cs
/// Interface all room behaviors needs to implement
interface IRoomBehavior {
    /// Check if this room is a behavior of this type
    public static bool FulfillsRequirements(Room room);
    /// Name of this behavior (is this a type?)
    public string Name();
    /// This behavior just got added to this room
    public void Added(Room);
    /// This behavior just got removed from this room (disassociate the furnitures
    public void Removed(Room);
}
``` 

We'd need to add some functionality to allow us to designate a room, but when we have it, we run the static `FulfillsRequirements` to ensure that the room has all the needed components. If it has, we add it to the list of behaviors of that room. We'd also need some additional APIs to room. Something like this maybe:

```
class Room {
    /// Get behavior by name/type
    IRoomBehavior Behavior(string name);
}
```

## Open Questions

  1. Who tracks possible behaviors? RoomBehaviorController?
  1. How do we designate rooms?

**Comment by abackwood** [comment]
2) Context menu on a tile in the room? The CM might need to be improved for this.
Alternatively and more visually clear: have a UI mode that displays the base on the room level - sort of an expansion on the room overlay - that lets you select rooms and set their behaviours

**Comment by vogonistic** [comment]
I think context menu is the best path right now until we make some fancier interface.

**Comment by TomMalbran** [comment]
1) If we want the RoomBehaviours to be moddable, we could go with an xml file and use the PrototypeManager to create all the RoomBehaviour prototypes. We can then have a RoomBehaviourManager if we need to keep track of additional information about all the Room Behaviours. Finally the RoomBehaviourController can be in charge of hooking the ui with the model, grab the click and add the Behaviour to a room, or ask the RoomBehaviourManager to do that job, if we need to keep track of a RoomBehaviour -> Room list, or some sort of list.

For the first part of the requirements, this will be easy since the xml can have those requirements, but when we add actions it might be more complex, but we can start adding events that can be hooked to a lua function.


2) I agree with @abackwood. The context menu item can open a small dialog with all the possible RoomBehaviours. We can also go with the Rimworld style of the room overlay that allows you to keep playing, but shows the room information.

**Comment by sboigelot** [comment]
The CM already support clicking on a Tile. The Tile implement IContextActionProvider, just yield a new ContextMenuAction from the Tile.GetContextMenuActions method ;)

**Comment by akomm** [comment]
What about not adding/removing behaviour, but applying it external via "apply" public method on the behaviour?

```cs

using System.Collections.Generic;

/// Interface all room behaviors needs to implement
interface IRoomBehaviour {
    /// Check if this room is a behaviour of this type
    public bool FulfillsRequirements(Room room);
    /// Name of this behaviour (is this a type?)
    public string Name();
    // apply logic on room, if needed using delta time
    public void apply(Room room, float deltaTime);
}

class RoomController {
    private List<Room> rooms = new List<Room>();
    // Or plain array, when we only need 1 instance of each behavior
    private List<IRoomBehavior> rommBehaviors = new List<IRoomBehavior>();

    public void Update()
    {
        foreach (IRoomBehavior roomBehavior in roomBehaviors) 
        {
            foreach (Room room in rooms) 
            {
                if (roomBehaviors.FulfillsRequirements(room)) {
                    roomBehaviors.apply(room, Time.deltaTime);
                }
            }
        }
    }
}
```

This would take away the requirement to manage adding/removing behaviors. Also the check for `FulfillsRequirements` might be quite fast, providing a proper API to access information about a room. 

This way feels more consistent, might be even faster, then it appears at first glance and less prone. The condition for a behaviour can change whenever model is changed and this can happen any time on update, so you will end up checking conditional whether to remove or add at the end of the day and it will be prone to inconsistency and errors, when you yet overlooked a case where you have to recheck rooms and/or trigger the event that is required for the check to happen.

**Comment by vogonistic** [comment]
@akomm I don't see how designating a room once is slower than looping over roomCount*behaviorCount on every update. The check might be fast, but it might also not be fast if the conditions are complicated and the room large. The other problem is that this doesn't allow state to be stored. The airlock problem was to have joint control and state. 

On a separate note, there hasn't been much discussion if we want any automatic room behaviors added yet.

**Comment by akomm** [comment]
@vogonistic I assumed you want the behavior to be dynamic, not designated on creation of the room. Am I wrong? 

If not: the condition for a behavior to apply on a room is not determined, we only have an public API to "ask" it whether the room fulfills the requirements of a behavior to be applied on it. Why do we have this public interface? So we can detach it from a room? But when do we check it to decide to remove it, and from where is it done? how often? Does every model have to know that there is a behavior that, when a specific model property changes has to be notified to so it detaches from a room? Then you would give the responsibility to the whole model from 100 places in the code and the model would have to be aware of concrete impl. and not just the interface. Maybe I miss some part of the whole system, but currently it seems like you might still have to check stuff later on from 10 places very often and this would be quite prone.

**Comment by vogonistic** [comment]
Sort of. I assumed that the user would designate the room an Airlock and can undo that designation at will. This will work for things like Meeting Rooms, Offices as well.

The reason for the API is so that when you try to designate a room, we can disable or not show Airlock if it doesn't have an Airlock Door.

I was thinking that we'd add it when the user designates it and we remove it either when the user decides to do so or when the room itself is destroyed by a broken wall or something else. We already have rooms and a room graph. When we remove a room from the graph, we'd call `Removed()` on each of the behaviors registered with that room.

**Comment by akomm** [comment]
Okay, now I got behind what the behavior should do. I thought it is something that implicitly is enabled or enabled on conditions in model, etc. But does it always make sense that the user has to explicitly designate it? For example if you put stuff that an airlock requires, what is the point for him to explicitly designate that it is an airlock? Because before my first comment on this I first wanted to ask whether it is a user designation or implicit and then canceled it out because I thought it would not always make sense (correct me if wrong :) )

**Comment by vogonistic** [comment]
It might not make sense to have everything be manually enabled, but it's easier to start from that place and extend it to be automatic in some cases.

**Comment by vogonistic** [comment]
I don't have time to start on this for a while, but this isn't a very complicated feature to add to the game. It's pretty well prepared for it.

**Comment by akomm** [comment]
Do you want to keep the behavior on a room even if it does not fulfill the requirements anymore? If not, you would have to trigger invalidation check for all rooms & its already attached behaviors and detach those that became invalid.

**Comment by akomm** [comment]
I think for that we would need some sort of managed for rooms, maybe not yet separate one for behavior, which keep tracks of rooms and has an public API `void revalidateBehaviors()`

**Comment by vogonistic** [comment]
Thinking of how DF handles it, you can say that it's an Airlock, but until you fulfill the requirements, you don't get the functionality out of it. We'd have to be able to explain to the user what is missing for that though.

For revalidating rooms, we could either do it lazily when features are accessed (like UI shown), or we could add an event that informs rooms when furniture has changed inside it. 

We also need a room overview to be implemented so that we can see the rooms we have and their info, but that is a separate task.

**Comment by akomm** [comment]
Okay, that would mean that the behavior does not itself implement any logic, but is just a tag which can be applied to rooms and can tell you whether currently the room fulfills its requirements? It does not "act on room" when it is assigned to the room? So it is not a problem if it sticks on it, even though requirements are not met at certain point? Otherwise it would have to check where it fulfills the requirements each time it wants to "provide" functionality.

**Comment by vogonistic** [comment]
No, the behavior needs to be an instance since it is a central control, so that when someone wants to open an airlock door, it will coordinate the opening of the door, pumping the air and opening the second door. It will probably need some state variables as well. It would be possible to put parameters in the Room and have a single behavior instance too.

It isn't the room, it's a set of functionality that might or might not be used in multiple rooms, but definitely not all rooms.

There is a different issue #1071 that would let us know when the room changes. We just need one for furniture changes as well.

**Comment by akomm** [comment]
So 

` it would have to check where it fulfills the requirements each time it wants to "provide" functionality, depending on the type of behavior it might be also something on each update?` 

is correct then? My example would be time based opening of doors in an airlock. 

Otherwise I do not understand how 
`Thinking of how DF handles it, you can say that it's an Airlock, but until you fulfill the requirements, you don't get the functionality out of it`

should be achieved. If a room is designated as an airlock, but is not an airlock the behavior would have to check each time whether it meets condition or not and since the example "opening doors" is something that goes over time and probably is happening over multiple updates, we would check every update.

**Comment by vogonistic** [comment]
If there is an event that gets called when furniture are changed in the room so we can rescan, all we need is a boolean for state to know if it's fulfilled or not when we want to use it.

**Comment by pderuiter77** [comment]
Sorry to be late to the party, but why not use zones to denote functionality? A zone would have requirements, so i.e. an airlock zone would require it to be enclosed(surrounded by walls / doors), have at least 2 doors and an air pump. 
This way you can make zones that are not room dependent (like i.e. a bedroom zone, which could be in the corner of a room)

**Comment by NogginBops** [comment]
Sounds like a good idea. Is there anytime this would break or not work? How should a zone be handled if one of the requirements suddenly disappear (eg a airlock door is destroyed)?

**Comment by pderuiter77** [comment]
If the requirements are not met, you could have a red border around it or red shading / warning sprite, denoting the zone cannot function. 
If a zone is red, it will not perform its programmed function, but furniture will be unaffected, i.e. if you remove 1 door, the other door will still be operable (with consequences of course), but the air pump won't be used by the zone. So you only 'break' the zone

**Comment by TomMalbran** [comment]
Prison Architect works like that by using zones (rooms).

If we use zones, does it make sense to separate a room into more than 1 zone? We can still use zones but if you can't mark the zone, and just select a room to add it a zone, then is the same as a RoomBehaviour.

**Comment by pderuiter77** [comment]
That's why i said in my comment that a zone could be a part of a room. You could make an entire room the bedroom, or just a part. If you want to get fancy, a tile could be part of multiple zones (with diminishing returns). So you have a bedroom, a bathroom (so the AI knows where it is logical to shower), all in the same room if you want (with a partial divider wall). A zone and a room are 2 different beasts. A room denotes an enclosed space. A zone denotes a functional area

**Comment by koosemose** [comment]
Closing as RoomBehaviors have been implemented
