### ISSUE TITLE
Git flow and feature branches

### ISSUE THREAD

**Issue by Skalicon** [TeamPorcupine/ProjectPorcupine#1054]
It should also be possible with the correct configuration to remove the need for forking which should dramatically improve quality of life for developers less familiar with Git. To achieve this we setup Git Flow so develop is the new main development branch and lock down develop and master to require PR for merging. Then allow normal users to create branches. This contains all code to single repo, makes all feature branches publicly available for collaboration, and allows moderators to help out other developers by routinely merging develop into their feature branches, helping with conflicts etc, which can be quite painful with forked repos.

On top of that despite the game not being released, keeping a stable master can be extremely useful. With GitFlow it is extremely simple to achieve this.

I am an experienced developer and have worked with Git in large enterprises, I'd be happy to help with version control management / configuration if required.

Vote here:
http://feathub.com/TeamPorcupine/ProjectPorcupine/+19

**Comment by vogonistic** [comment]
Githubs permission scheme makes it hard for us to allow automatic merge of PR's against particular branches. The way we have been working on some larger features previously is to do it on a forks branch which then can be used for a PR against the official repo. It puts the merge capabilities in another users hands and makes it possible for them to allow Collaborators at will.

**Comment by Skalicon** [comment]
It should also be possible with the correct configuration to remove the need for forking which should dramatically improve quality of life for developers less familiar with Git. To achieve this we setup Git Flow so develop is the new main development branch and lock down develop and master to require PR for merging. Then allow normal users to create branches. This contains all code to single repo, makes all feature branches publicly available for collaboration, and allows moderators to help out other developers by routinely merging develop into their feature branches, helping with conflicts etc, which can be quite painful with forked repos.

On top of that despite the game not being released, keeping a stable master can be extremely useful. With GitFlow it is extremely simple to achieve this.

**Comment by Skalicon** [comment]
I agree that this would open up the possibility of having people interfere with feature branches. But I think that it is worthwhile to improve transparency, collaboration, and ease of use.

**Comment by vogonistic** [comment]
We can't use protected branches even if we want to unless we get a proper CI setup. If you want to help us set that up, that would be awesome. 

Make sure you read up on what kind of permissions can be set up on github as well.

**Comment by Skalicon** [comment]
Hey @vogonistic I'd be happy to help with CI. This wasn't previously possible in GitHub but we can do it now with Protected Branches, so there should be no reason that we can't implement this.

**Comment by Skalicon** [comment]
I'm also an experienced units/feature test developer, maybe I could take this on as my first project.

**Comment by bjubes** [comment]
ive been trying to investigate CI as well. I can make unity build from command line fine but the problem is getting unity installed on someting like jenkins or Travis. you can see #73 for what has been previously done.

**Comment by koosemose** [comment]
Would this prevent someone from forking and doing PRs from their own fork? I much prefer working from my own fork for organizational and convenience purposes. It seems like it would be a bit of a pain to do a PR and have to search through the entire list of every branch someone has made, and may be an old already merged branch that wasn't deleted, or a branch that someone was testing something on or abandoned and never deleted.

Additionally you say it would be publicly available for collaboration, does that mean if I were working on a branch of the main repository someone could just come in and change something either without fully understanding the code (either due to not reading the documentation, or the documentation not being fully in place due to it being a work in progress) or just because they think it should be done differently, and I either have to go back and undo the commits or manually change the code they changed?

**Comment by Skalicon** [comment]
@koosemose This does not prevent forking or merging from forks.
PRs can be configured to delete branches once merged and should be configured to do this, however yes you would need to use the search tool to find your branch, trust me it's not a big deal.

The code would be publicly available, which I agree is a problem, especially because this is a public Repo. The solution is, as you already mentioned, to continue to work in your own fork if you don't want collaboration. However, it is good practice to have your code pushed so your team can collaborate at any time. As a programmer you do need to learn to trust working with other developers when working in a team. If we were using bitbucket we could fix a lot of these issues, but for now we just have to deal with GitHubs limited permission system.

**Comment by Skalicon** [comment]
We do really need to set GitHub in a single Repo if we want to be able to do CI properly, which does cause the issue of allowing the public to mess with branches, to fix this, we may well need to white list people for the project or certain feature branches, so that, while other people can, branch from your feature Branch and PR to suggest changes / additions, only whitelisted developers can actually make feature changes directly to the feature Branch. Not ideal, but neither is having open feature branches, it just depends on how we want to do it.

**Comment by koosemose** [comment]
If we were working in an enterprise environment, or any form of closed dev team I would agree with you, but we're not. Even if it was just the current contributors, we have 90+ of those the last I looked and I have a passing casual knowledge maybe 10 of those, and a deeper knowledge of maybe 3 of those enough to trust their coding and or wisdom to stay out of code they don't yet understand. I don't really see the benefit of the branching scene you propose, as a git newbie it was trivial to do the forking method and anything I couldn't figure out was explained, the same as working with branches within the main project will likely need some things explained.

But, if this doesn't prevent me from working with my preferred flow I certainly don't mind it becoming an option.

**Comment by Skalicon** [comment]
Koosemose, the main problem is CI, the reason it doesn't work is that when you create a PR from a fork, the git repo doesn't own that code yet until it is merged. This is a problem, because we need to pass this code to our CI build script which will essentially check to see that the project still works after that PR is made. This is a difficult problem to overcome.

**Comment by vogonistic** [comment]
I want to drop the discussion of moving away from pull requests and a pure git-flow. GitHub is built around the pull request model and it would be a waste of time to fight it. 

Pull requests do trigger Travis builds and it works because GitHub creates a special ref for the PR so it looks like it's available through the main repo. I'm going to continue the discussion on #73

**Comment by koosemose** [comment]
This is based purely on reading the travisCI docs ( https://docs.travis-ci.com/user/pull-requests ) so I don't know if this is the case for all. But in their case it is because it is a security risk to allow a build from anybody(as can be the case with a PR from a fork) but with my understanding if we're allowing anyone to make a branch and PR from it, that same risk still stands. And if we close it to only a limited set of contributors, that seems to run counter to the nature of the project.

**Comment by Skalicon** [comment]
@koosemose & @vogonistic The issue is not with the CI tool but with Unity Cloud Build tool, which requires code access / authority to run builds since it works directly with the repository. There are other ways to solve this issue and work around the forked branches issue so I am going to close this topic as I agree that using a single repo method is not the best idea. However, git flow is separate from this and absolutely should be implemented, we can discuss this later though.

**Comment by vogonistic** [comment]
@koosemose A note on the security. We don't have any secrets as variables or in any other form, so we don't have to worry about someone making a PR to steal them, which is the concern they raise.
