### ISSUE TITLE
Fundemental Game Play- Movable Base or Expedition model (Asteroid gameplay mode)

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1070]
In virtually every conversation I've had with people about the game, including #1023, the popular idea has been for the game to take place in the asteroid belt, or some other similar location with lots of asteroids. In discussing this at #gamedesign, we've come up with 2 proposals that are somewhat realistic, meet the asteroid objective, and allow for open play, all of which have been listed as desirable. The two models are:

Plan MOVE SHIP- The "base" is really a ship. The ship goes from Asteroid to Asteroid, mining fuel and resources from each one. What is mined will be dependent on what is in the asteroid. I kind of have a vision where the asteroid is a background layer that we can see, and we line our ship up with the resources that we need from the asteroid. We then dock with that asteroid, and get all of the resources from it we can. We fuel up, and move on to the next one. Each asteroid will have some unique materials, which will expand the game play gradually. The asteroid field will probably be infinite.  You will get to choose which asteroid to go to next. There will be some indicators, like predicted composition, size, fuel cost to get there, hazards, but you won't know for sure what you have until you are there (Or have really good sensors)

Plan EXPEDITION- The main base doesn't move. It does create ships that are sent out to other asteroids periodically to mine goods. It might involve keeping track of many resources at the same time.

What I would like from you all is to decide which plan you would like. If you have an alternative proposal, feel free to discuss it with us at #gamedesign at Discord, or mention it in your reply, but as much as possible I would like to keep this thread clean. Also feel free to discuss it at #1023. Let's keep this open for several days and see what the consensus is, and then let's move forward full speed ahead form there.

**Comment by kd7uiy** [comment]
My preference is MOVE_SHIP, with an eye towards EXPEDITION. I think the MOVE_SHIP path will be easier in the short term. I think at some point we might need to split the base, but having multiple operations occurring at the same time would make things confusing, at least to me.

**Comment by dusho** [comment]
I guess MOVE_SHIP for me. You can still gather resources in different places, upgrade and expand your ship, build more devices, better engines. EXPEDITION sounds like lots of micromanagement + uncertain about base handling when you're on expedition.. So ye.. maybe flying mothership is even simpler approach..

**Comment by vogonistic** [comment]
I'm MOVE_SHIP, but I'm having big reservations on the mining, which I've outlined in #1060.

**Comment by koosemose** [comment]
I feel like MOVE_SHIP is a very drastic change from the idea of base building. It makes it feel more like a subpar exploration game. You can customise your ship, but then you're basically going to waypoints in which your "ship" is stationary. 

I much prefer plan EXPEDITION, get information about local asteroids (possibly another use to mining drones, in addition to slow resource gathering, they could be used to provide a sample of what a given asteroid contains), and then you either go there with several crewmembers and just mine up as much as you can, or set up an automated mining operation (maybe a little of both), or possibly just set some workers to mine that area, and they "Work" a shuttle, which goes away from your base, and you can either leave it at that, and they work at some rate based on attributes/skills, or you can follow them there and micromanage and leave your base to be automated.

Though I do think it could be interesting to have some bit of movement, at a relatively big cost (of time or resources), but rather than moving from asteroid to asteroid, it's moving "zones" or orbits, so you might start off orbiting in/around an asteroid belt, where it's easy to get to asteroids, and then spend a big bunch of fuel (or something) to change your orbit to one of the inner planets, when you discover one of them has some resources you can't easily get otherwise. Now you can more easily get resources from that planet, but getting an expedition out to the asteroids is much harder.

**Comment by FraserKillip** [comment]
I think I would prefer a hybrid of the two almost.

**Comment by Tranberry** [comment]
I'm with plan EXPEDITION as the alternative **seems** to me to be another kind of game to what **I** understood the game to be. I didn't really see why so many people confused *base* with *ship* in the begging now I think I do.

I'm just pulling this out of my **** but I believe the MOVE SHIP is just star trek with mining which many of you probably adore.

---

I'm not really against any of these ideas, I'm just against moving away from the initial description _"A Base-Building Game...in Space!"_ at a too fast pace.

**Comment by springmouse** [comment]
I'm with plan EXPADITION to, because personal i like the sound of having a centralized base that i operate out of controlling everything. and plan MOVE_SHIP as has already been stated sounds like a completely different game to our initial concept. but as both FraserKillip and Koosemose have said i cant see a reason not to have aspects of MOVE_SHIP in the game.

**Comment by koosemose** [comment]
Again laying out some of my thoughts from a Discord discussion that is apropos here. Regarding moving the base. As I've said, I prefer the idea of a mostly stationary base, where you CAN move it but at something of a cost. My ideas regarding the gameplay/story surrounding moving your base is as follows:

You initially arrive in system using your quillcorp basic utility station's one-use orbital insertion launcher. By either ordering a new one from quill corp (at a hefty fee) or by hacking and repairing and otherwise tweaking your original one, you can pour lots of power (and resources) into it to get another use out of it, but it only has a limited range (so you no longer get to pick ANYWHERE in the system, but rather within maybe 1 orbital range), the second is cheaper but more catastrophe prone.

**Comment by kd7uiy** [comment]
Okay, there seems to be quite a bit of interest in both. I think the way to manage this is to allow for expeditions and a moveable ship. This also likely works better for the loose ideas being proposed of having different locations for the base, each with their different needs. Also, I really suspect that once the base gets to be a certain size, moving it would become impractical, so having a means to get resources without moving the entire base seems like a good idea.

**Comment by abackwood** [comment]
If these are the choices, I'm on the side of Expedition, though I have some doubts about the expedition mechanic.

I think trade will simply become more important as your base grows. No complex economy can survive on its own. You need imports and exports. The expeditions are, in my mind, then just a more controlled form of trade. You send your people out to get you goods from outside in exchange for manpower and fuel.

I think maybe a mid- to late-game mechanic can be that you can shift orbits with a high cost, but anything more movable than that breaks the high concept of the game. We're building a base not a ship.

**Comment by mikejbrown** [comment]
> We're building a base not a ship.

Agreed. I vote Expedition, with the possibility of rare, high cost and high risk moves of the base. In terms of sci-fi precedents I'm thinking Star Trek DS9 and Stargate Atlantis. In both series they moved the station once in an emergency situation and it nearly destroyed the place.

**Comment by kd7uiy** [comment]
Okay, I've posted my summary of things at https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Asteroid_base . I'm going to say as there is lots of interest in both ideas, let's let both ideas progress further down the line, and see if one is more viable than the other, or if we can include both modes of play.

**Comment by pderuiter77** [comment]
Why not use both? Start with EXPEDITION, having a base to start from. 
Then allow the player to build a ship..

**Comment by NogginBops** [comment]
I like what @pderuiter77 is thinking!

**Comment by kd7uiy** [comment]
I've included the notes on the wiki, and given it plenty of time to comment on them. Let's open a new issue if we want to discuss things further.
