### ISSUE TITLE
Travis CI not updating on outstanding PRs when a PR is merged

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#1154]
So something a little interesting happened in #1137. I wrote some code using an API from another part of the project. Then, later another PR was merged into master changing that API. This did not directly affect any of the files I modified so it was correctly flagged as a clean merge. _However_, it did cause compile errors (which is fine). The problem is that the CI wasn't rerun on my PR so it was still showing as a passing test.

Is this desired behavior?

I can't really think of an alternative other than rerunning CI on every outstanding PR each time a PR is merged, which might be too much of a computational burden on the system (or could get that way in a busy season). But it does detract from the value of that green check mark somewhat.

**Comment by bjubes** [comment]
I think recompiling every PR on every change would overburden travis, thus why the check mark stays. However, this mistake would be caught by a gatekeeper when testing, and if it was merged, travis would then pick up on the issue. Also if you rebased your changes, travis would recompile and find the error.

so technically, the check mark means "this passed merging into master at the time this commit was pushed."
If anyone knows how to make travis recheck, please say so in the comments. Otherwise this is a minor pitfall of CI that gatekeepers will easily catch when the test

**Comment by vogonistic** [comment]
I think travis doesn't build the PRs merged with master anyway. It just checks that on the branch itself, as submitted, there isn't anything wrong.

**Comment by kd7uiy** [comment]
That's certainly how I would do it, only check the branch itself. Interesting that it didn't cause an error, that's probably a sign that more unit testing is probably required. Hmmm...

**Comment by bjubes** [comment]
for PRs it merges and checks, for branches it merely builds. for a pr from a branch in the same repo it will do both

**Comment by koosemose** [comment]
Closing this as there is little we can do to change how travis tests things.
