### ISSUE TITLE
[Bug] Furniture jobtime reset after loss of power.

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#1161]
There seems to be a bug, where the job time is reset, if power goes out. This applies to at least the Cloning Pod in Lua. I'm not sure if this is a general problem with all furniture, or just some of them.

**Comment by koosemose** [comment]
While it is currently a bug, it kind of makes sense for powerloss to cause lost progress on at least some things. Like if you're creating a clone, and lose power, the clone isn't going to be viable and would die

**Comment by TomMalbran** [comment]
The issue is that the jobs are canceled when the furniture has no more power. and recreated once they get the power back. For jobs that are about getting inventory, it makes sense, but for other it doesn't. Maybe we should just pause all the jobs instead of cancelling them, or save the job time and set it back when recreating a job.
