### ISSUE TITLE
Metal smelter doesn't update it's job once it's done

### ISSUE THREAD

**Issue by frankitox16** [TeamPorcupine/ProjectPorcupine#1178]
Preety much what it says in the title, it smelts 50 iron ores and then thats it... Have to make another metal smelter in order to smelt more?

**Comment by Tritaris** [comment]
Hmm that is not the issue I am seeing here. I believe the problem is due to not be able to find the required raw iron for the job. If I place a smelter down with no raw iron on the map and then go mine the iron mines it wont see that iron. If I place it down after mining the iron it then see it and will convert more than 50 iron ore to steel plates.

**Comment by frankitox16** [comment]
Isn't that search driven by the job? Or maybe the problem is that it's waiting for 50 iron ores, but if you have less it won't go on smelting.

**Comment by jaselito** [comment]
This seems to have been resolved somewhere along the way...
