### ISSUE TITLE
RTGs

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#1210]
With artwork for RTGs being discussed in #1209, a lot of questions have come up about what we should do with RTGs overall. Some of these include:
- Do we allow for refilling RTGs?
- Should the energy be constant, or near constant, and gradually go down, as real RTGs do?
- Should there be recycling perhaps? Maybe filling the RTG can only happen in the same facility that manufactured the device, but a refill will be quicker or cost less than the originally made RTG?

I'm sure there are others, but I wanted to get the discussion started here.

**Comment by ComputerOverlord** [comment]
I dunno :P 
Buut... if there was a fuel--what would it be?

**Comment by kd7uiy** [comment]
Plutonium is the fuel, an artificially made substance, made from Uranium. You could in theory have a factory that takes Uranium, makes Plutonium, and then pack that in manually, but I kind of like the idea of taking the fuel cell to some sort of a factory, I think replacing the fuel in the field would violate OSHA regulations;-)

**Comment by mikejbrown** [comment]
Quillcorp care about OSHA? Tosh :laughing:

**Comment by kd7uiy** [comment]
Hence my smirk at it. Still, I suspect it'd be pretty dangerous... It also would be something to really distinguish it from other forms of power, something to keep in mind.

**Comment by koosemose** [comment]
A proper RTG should have a lifespan such that it shouldn't ever need refueled within a reasonable play time. It shouldn't generate near the amount of power as a fission reactor, the primary benefit is that it lasts forever, and as long as you don't damage it, it should be relatively safe. 

I personally see it being relatively late game, similar in role to a solar panel, with a smaller foot print (possibly other concerns, like preventing it from heating up if you keep it inside, which would reduce efficiency).

Theoretically resources to create it could be created as a byproduct of the Power Generator (which in its current form is basically a nuclear reactor). It's just going to be a relatively slow process.

**Comment by kd7uiy** [comment]
If we take away any kind of degradation in power over time, we have to limit the power somewhat. RTGs typically don't produce all that much power, and cost quite a bit to boot. If we wanted to have them be realistic, they would be the source of power for a spacecraft perhaps, or something off the power grid. Hmmm... That something wouldn't be able to use a lot of power either.

**Comment by koosemose** [comment]
That's basically how I'm seeing it, a slow but steady power source, either on a separate grid to power something you can't afford to have go offline (various life support functions), or to just to add a little steady bump for your regular grid... maybe feed into a capacitor for something that you won't use often... possibly an emergency power system that will always work but won't be able to power high draw things.

**Comment by kd7uiy** [comment]
A capacitor could be a separate thing. I would think these would provide heat and a constant amount of power with no need to update, but both of them being somewhat limited. While you could hook it up to a capacitor, that seems a bit more of an abuse, although a separate battery bank or capacitor bank could be interesting. Hmmm...

**Comment by koosemose** [comment]
There's already something that's functionally a capacitor in game ( assuming I understand how its implemented), it's the accumulator. 

And I'm pretty sure the RTG already generates heat, we might want to make it so that energy production goes down as heat rises, so they either have to be built outside where they're vulnerable, or inside and you have to deal with the heat.

And if we're able to store power, there's no reason you shouldn't be able to store power from an RTG, it's still going to be a relatively small trickle of power, and still probably best used as a separate power source for things that you don't want going down if main power is lost.

As a whole we need to look at a rough plan for power generation, as is, I think the numbers are likely all over the place, and we need to look at a rough plan of progression of power generation, and what roles we want filled. The roles and progression will seriously affect what is reasonable to set up a power source to do. For example, if the Power Generator (nuclear) is intended to be early game power, then it needs to continue to be relatively easy to fuel, and not incredibly long lasting. However, if it's later game, we could require more processing to make fuel usable by it, and further have it's by-products used to produce the RTG, So nuke would serve as late game high energy source, and RTG would be late game constant slow energy source. We would then of course need to have some other believable early game resource... and kind of fired generator (such as coal or gas) would be a bad idea on a station, but surely there's other reasonable methods. And since this is presumably supposed to be futuristic (what with space and all), we could get into extreme late game tech with things like a fusion reactor, antimatter reactors, Zero Point Energy collectors, and whatever other techs we may dream up. Basically it's hard to come up with a reasonable plan for a specific energy generating device without at least something of an idea about general progression and roles of energy generation.

**Comment by kd7uiy** [comment]
I like the idea of having the RTG provide less power if the external heat is too high, and for it to naturally head the outside. Storing power from another related device seems quite handy, and I agree, if it works for one, it should work for all. I just didn't want to see an RTG store energy by itself.

It's pretty common this early in the game to not have anything be balanced, and that's more than okay.

**Comment by mikejbrown** [comment]
For early game a realistic option besides solar is a fuel cell which converts 2 H2 + O2 -> 2 H2O + energy (and possibly also an electrolyzer which does the reverse). This gives a potential trade off mechanic for rocket propellant and oxygen vs water and power.

**Comment by Tritaris** [comment]
for the phyics behind the color choice, here is some reading material: https://en.wikipedia.org/wiki/Black-body_radiation

**Comment by Tritaris** [comment]
https://youtu.be/zPwhMUfbuh0

**Comment by pderuiter77** [comment]
And what would stop players from putting it on a room with 1 tile open to the outside? Wouldnt that lose the heat with no risk?

**Comment by Tranberry** [comment]
@pderuiter77 that's what satellites do now. I'm not sure I understand what you mean by risk though.

**Comment by pderuiter77** [comment]
Risk might have been the wrong word. But i meant there is no longer a downside. Since the rtg isnt heating up, Because it is in a room exposed to the outside, the heat mechanic is circumvented. And because its in a room, its not in any danger

**Comment by koosemose** [comment]
It's in *less* danger in exchange for having to deal with either an empty spot with no atmosphere in the middle of your base, or having a growth off the side of your station solely for that purpose. Nothings to keep it from being attacked by pirates. 

And either way, it's still going to be a very low amount of energy.

Obviously most of these details aren't accurate as of this moment, numbers on everything need to be balanced.

**Comment by pderuiter77** [comment]
You're right. no more objections :)

**Comment by Geoffrotism** [comment]
well not entirely true about heat. The RTG would still transfer heat to the surrounding walls. Thermodynamics is annoying as crap to deal with though. I'm not sure how simple or complex we want to make this game but what if the player decided to make the RTG in the middle of a room? we would still need to calculate heat transfer in that case. :/ maybe force players to place RTGs in a tile adjacent to space?

**Comment by pderuiter77** [comment]
The best way would be each tile separate. Same with gas pressure. If the temp/ pressure is lower in a neighbouring tile, increase it.
But we need to make that as efficient as possible, like only update it if a neighbouring tile is changed

**Comment by kd7uiy** [comment]
I suggest the aspects relating to heat should be taken to #298 .

**Comment by vogonistic** [comment]
@pderuiter77 I worry about how efficient you can make that. What if we have a wall blown in by space pirates and the base is 500+ tiles. How much effort is it worth spending on knowing heat on a per tile basis and what is the big benefit vs just having a single value per room?

**Comment by pderuiter77** [comment]
Thats why you only update when needed. Whem a tile changes it will signal its neighbours to update, making it a cascade. 
perhaps performance is an issue. And maybe it isnt. Wont know till we try. If you dont make the calculations too complex. Even just averaging the temp between 2 cells should work

**Comment by vogonistic** [comment]
The cascade in a large base is what worries me. That said, I'm all for testing it if someone wants to make a PR on it.

**Comment by mikejbrown** [comment]
That's effectively solving Poisson's equation iteratively, which is... slow. Fast algorithms use spectral methods which I doubt would map well to the arbitrariness of the bases you could build, unfortunately. You could try something like the finite element method instead, but I bet that's probably harder than it would be worth.
