### ISSUE TITLE
Liquids and gasses Network, Grid and Connection

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#1240]
Right now they serve only as `PowerNetwork`
As we plan to have more types of `Network` (Air, Water ...)
I would really like you people to write requirements to the system
What they should be capable of and so on.
Thank you.

**Comment by mattpott** [comment]
What would an air system look like? Isn't air handled by the tiles?

**Comment by koosemose** [comment]
The more I think about it, the more I think that you may have been right in that they should be implemented separately, at least fluids (liquids and gases) may need to be separate from power, since as I understand our power system, it overall works on a system of having a total capacity it can output, and as long as that capacity is met everything is fine, and anything not consumed (either by a machine or by an accumulator to store it) is essentially wasted. Whereas fluids are probably going to need to worry about a total amount in the system, and it wouldn't make too much sense for water, for example, to just disappear if you produce more than you consume.

**Comment by koosemose** [comment]
@mattpott While air is stored in a room, it may be desired to be able to actually pipe it around you base, rather than relying only on natural airflow between rooms (through doors leaking, or vents if we implement those). 

This becomes even more significant if we begin having things that need an air mix other than O2/N2, such as if we have alien species, or perhaps some other reason for having a different mix, where we may not be willing or able to produce the appropriate atmospheric mix in the same area we want to use that mix (such as if you have a section for alien visitors, but want your people to be able to work on the gas mix producing equipment, without needing environmental suits. If we can pipe it around, we could then produce it in a human accessible maintenance area, and then pipe it to the alien section.

**Comment by Grenkin1988** [comment]
@koosemose Yeah, for me this should be different system. That's why I ask to gather information about what we need, in order to decide how to solve this.

**Comment by koosemose** [comment]
Working on a discussion in discord figuring exactly what we want to be capable of. Will report back with anything useful we come up with.

**Comment by koosemose** [comment]
Ok, so nothing immediately pertinent to this has came up as of this point, due to the differences in power and other things we might want to transport, power will likely have to be separate from the others, however I think everything else can be done as generic fluids and it be up to the machine using them on how to treat them, or liquids and gasses being separate (though they would have more in common than they would with power) so we could be certain that liquids are treated as liquids and gasses treated as gasses.

As for what they need different from the current power implementation, they need to not have liquid produced or stored go to waste and disappear if there is more produced than used (the machine producing them or putting them into the network should stop if it has no more capacity).

They also need to know what they are. For liquids it would be reasonable to have just something as simple as "Water" or "Waste". For gasses it would be useful to have a way to define it as a mix (so one network might specifically contain O2/N2 atmospheric mix and the ratio, and another some other mix). It may potentially be useful to know the pressure of the system, but sure if we actually want information beyond what it is, how much total there is, how much capacity, and the flow rate (in and out).

**Comment by mattpott** [comment]
Depends is the game going in the direction of needing a specific waste component? From a game mechanics perspective we could just say that the water system also carries away the waste water.

I am thinking of implementing the water system this weekend, if nobody was already working on it.

**Comment by mattpott** [comment]
For a liquid system, I was thinking of using a simple pressure + flow system not quite sure on the specifics yet.

**Comment by fre-ber** [comment]
Another network type that could possibly work the same way as the power grid is a data-network. Some devices might require a connection to a server, or even a link to the home planet "Internet" to function. For this network type, the capacity would be the throughput bandwidth in Gbit/s or something. Just an idea.

Having a separate moidel for fluids/gasses sounds reasonable as the "physics" for those are quite different.

**Comment by koosemose** [comment]
The main reason I mention something like a waste fluid, is that (assuming human waste, rather than toxic waste or some other sort) it could be used to reclaim water from, so the player doesn't have to constantly get more water/ice from somewhere.
