### ISSUE TITLE
ArgumentException in Tile::PlaceUtility when placing furnitures already installed

### ISSUE THREAD

**Issue by Ohda** [TeamPorcupine/ProjectPorcupine#1452]
There is a bug when placing some utilities furnitures.
Some caracters can try to call place some furnitures already installed.
This throw an error :
Utilities.Add(objInstance.Name, objInstance);
ArgumentException: An element with the same key already exists in the dictionary.
This happen pretty often ( 1 per 20 mabye.)
This was already on master before https://github.com/TeamPorcupine/ProjectPorcupine/pull/1350

`Tile.PlaceUtility (.Utility objInstance) (at Assets/Scripts/Models/Buildable/Tile.cs:237)
Utility.PlaceInstance (.Utility proto, .Tile tile) (at Assets/Scripts/Models/Buildable/Utility.cs:247)
UtilityManager.PlaceUtility (.Utility prototype, .Tile tile, Boolean doRoomFloodFill) (at Assets/Scripts/Models/Buildable/UtilityManager.cs:61)
UtilityManager.PlaceUtility (System.String type, .Tile tile, Boolean doRoomFloodFill) (at Assets/Scripts/Models/Buildable/UtilityManager.cs:49)
UtilityManager.ConstructJobCompleted (.Job job) (at Assets/Scripts/Models/Buildable/UtilityManager.cs:86)
Utility.<ReadXmlBuildingJob>m__2B (.Job theJob) (at Assets/Scripts/Models/Buildable/Utility.cs:469)
Job.DoWork (Single workTime) (at Assets/Scripts/Models/Job/Job.cs:263)
Character.Update_DoJob (Single deltaTime) (at Assets/Scripts/Models/Character/Character.cs:730)
Character.Update (Single deltaTime) (at Assets/Scripts/Models/Character/Character.cs:347)
CharacterManager.Update (Single deltaTime) (at Assets/Scripts/Models/Character/CharacterManager.cs:95)
World.TickEveryFrame (Single deltaTime) (at Assets/Scripts/Models/Area/World.cs:537)
TimeManager.InvokeEvent (System.Action1 eventAction, Single time) (at Assets/Scripts/Models/Events/TimeManager.cs:198)
TimeManager.Update (Single time) (at Assets/Scripts/Models/Events/TimeManager.cs:131)
WorldController.Update () (at Assets/Scripts/Controllers/WorldController.cs:144)
`

**Comment by koosemose** [comment]
Hmm... I could've swore I had checks in place that would prevent this... I'll look into it.

**Comment by koosemose** [comment]
Alright, the main issue is simply that there isn't currently a check for utilities if there is a pending job of any sort... mainly because I didn't implement it because pendingJob doesn't quite suit the needs of utilities (you should be able to queue up 2 different types of utilities to be built on a single tile, along with a furniture, but pendingJob can only contain one thing.

We need to either make pendingJob some sort of collection, and adapt furniture's check for pending jobs to deal with that, and be able to be built over things it should be able to be built over (such as pending utilities) and implement it in the first place. Or have some sort of job manager which, along with whatever else, can be queried if there are any building jobs assigned to a particular tile, and check things against that.

**Comment by koosemose** [comment]
Unless I'm mistaken this was fixed in #1575
