### ISSUE TITLE
Game preloader... Needed for v0.1?

### ISSUE THREAD

**Issue by frankitox16** [TeamPorcupine/ProjectPorcupine#1493]
Watching quill's last video noticed that the game takes a lot to load (even in a beefy computer, up to now I thought it was my pc). Do we need to add some sort of game preloader now (maybe after #1461 gets implemented?), or we can push it for future versions?

**Comment by bjubes** [comment]
how would a preloader increase compile time? Im pretty sure everthing would still have to be compiled in the same manner as far as playing inside the editor is concerned.

**Comment by mikejbrown** [comment]
Not for v0.1. Could be useful when there are a lot of mods though. I agree with @bjubes. Right now the only loading that really needs optimising AFAIK is the localization. Don't think we can speed up the compiling in Unity. (Please correct me if I'm wrong.)

**Comment by bjubes** [comment]
your right @mikejbrown , technically  you can use dlls to speed things up by recompiling code, but that gets very messy and isn't feasible at this point in time since so much code is still subject to change.

Preloading won't make 0.1, were already 5 days late so we can't really add large additions to it. of course the general rule still stands that you can implement it anyway regardless of whether its on the milestone or not.

**Comment by frankitox16** [comment]
Oh, didn't take compiling time in mind lol... But it is true that when modders go crazy, loading time will be greater, so when we focus modding will be the time to implement it, I guess.

**Comment by frankitox16** [comment]
(Closing this issue for now, too)
