### ISSUE TITLE
Localization not being applied on startup

### ISSUE THREAD

**Issue by mikejbrown** [TeamPorcupine/ProjectPorcupine#1502]
Change the language to something other than en_US, then save settings and restart the game. No errors are thrown but the localization is not applied. The correct files are loaded on start but for some reason the UI isn't being set to use it. Clicking apply in the settings menu still changes the localization as expected.

According to @koosemose:
> It seems to go back at least as far as #1468

**Comment by koosemose** [comment]
So it appears the issue has existed for a long time, possibly since localization was added.

Localization only seems to be updated when new language files are downloaded (such as happens when Assets\StreamingAssets\Localization\curr.ver is missing) or when the language is actually changed. Prior to english being repatriated and falling back to english we would see the unlocalized strings, so it would appear to be a different problem from this.
