### ISSUE TITLE
Settings DialogBox don't save if game paused

### ISSUE THREAD

**Issue by Ohda** [TeamPorcupine/ProjectPorcupine#1525]
There is a bug when the game is paused, the settings panel doesn't save correctly.
The problem come from here : 
`ScheduleEvent("Settings_SaveSettings", Time.deltatime)`
only happen on
`TimeManager.EveryFrameUnpaused`

This timer has been added in the game in #1490.

### Steps to reproduce the behavior

- set on Pause (spacebar) 
- Open settings panel.
- Make a change
- Save 

### Related issues / pull requests
I've got a problem with this issue on the intro scene, because the game is paused.
Feel free to give me tips or do a pull request to fix it. I'll be really happy to merge it on the intro scene !

**Comment by mikejbrown** [comment]
> I'll be really happy to merge it on the intro scene !

Since this is a separate issue it should be fixed in its own PR.

I see a few possible fixes:

1. (Hackish) Explicitly update the Scheduler from the dialog box in the intro scene.
2. (Better) Implement a version of SaveSetting that saves immediately for use only by the intro dialog. This will again have the lag issue.
3. (Best) Implement a method to save a bunch of settings at once (e.g. pass it a list of settings changes), writing to disk immediately. This fixes the original issue of multiple settings being written per frame in a different way.

**Comment by Ohda** [comment]
> Since this is a separate issue it should be fixed in its own PR.
I've go multiple problem with the settings panel so it's hard to test/understand what is good or bad in my PR.
I've spend one hour yesturday to understand this issue and identify that was not coming from my side.
I will come back on this tommorow evening !

**Comment by koosemose** [comment]
Rather than a method passed a list of settings changes, we could instead not have setting a Setting automatically save the setting (or schedule them to be saved) and instead just explicitly call SaveSettings. I believe this would have a similar effect to @mikejbrown 's 3rd option with less rewriting needed.
