### ISSUE TITLE
[Bug] Unreachable Wall job loop

### ISSUE THREAD

**Issue by Jaytheway** [TeamPorcupine/ProjectPorcupine#1536]
Characters stuck in a constant loop of bringing a steel to the unreachable Wall job and then taking it back.
![untitled](https://cloud.githubusercontent.com/assets/22476284/19397634/4b4196d4-9251-11e6-96cb-2539bb8e5cd8.png)

...on the picture above: Blue guy just standing still, others are coming with the pieces of steel to where the Blue guy standing, spazzing out and go back to a stockpile. I think it might have something to do with a not canceled job.

It was reachable, but somebody put a walls that covered this spot, when Blue guy was walking to it (if I remember correctly).

**Comment by koosemose** [comment]
Interesting... I thought crew could still build diagonally in areas like that... I kind of though that was proper behavior as it can help minimize situations like this...

**Comment by Jaytheway** [comment]
I thought so too

**Comment by BraedonWooding** [comment]
Well that should definitely be changed, we should be careful of implementing a change to minimize situations.  Okay, so whenever an object is placed could we do a search to do if it's in the way of any paths?  If so cancel paths?  Or whenever we look for next tile we look for tiles surrounding that with jobs, if so then we can just pretend that they have been built?  But that has huge problems with deconstruction.  So we could just do a semi-omnidirectional search after every move (7 tiles only since the tile you came from we don't need to check).  It wouldn't be slow and we could even do background then come back to main IF a problem occurs to rebuild path. The problem with this is still speed if character is insanely fast (ms per square) then it could still occur, so we need a better solution.

**Comment by koosemose** [comment]
Solution needs to be on the Job system. 

If a Job is unreachable it should be put on a secondary list (I believe this already exists, but is currently only used for a very limited set of scenarios. However, this isn't a simple process, as defining how a job is unreachable could be difficult. A room with no exits seems obvious, but if there is a character in there, then they can reach it when no one else can, and two rooms that have an exit between them but no exits to anywhere else, they would qualify as having exits, but not be reachable. 

It would help if, when a job is requested, a character could include the room they are in, and the jobqueue uses the room graph to figure out if they are on a connected series of rooms (taking into account a job which is between rooms, such as deconstructing a wall, and only give them jobs they can reach that way.)

It would also be beneficial if a character could "remember" jobs that failed for them, and perhaps tell the jobqueue they don't want any of those in some fashion.

**Comment by BraedonWooding** [comment]
I saw something about re-doing Job System is this something that should be done after that ?

**Comment by koosemose** [comment]
After or part of that

**Comment by ComputerOverlord** [comment]
[Bug] ... (bug label) is redundant

**Comment by Geoffrotism** [comment]
This is me thinking things through. Characteristics of a system we want or specific cases
we want to address (some might be a characteristic we already have but it's important to list everything out):

[] if a character can reach a job and has enough materials: do job.
[] if no characters can reach a job, stop trying to do the job until it can be reached.
[] if only a subset of characters can reach a job. Stop trying to do the job for characters that can't reach the job. 
[] if a job couldn't be reached before, but can be reached now, let characters from to do the job again.
[] if there aren't enough materials to do a job... (suggestions?)

What other cases are there?

**Comment by koosemose** [comment]
The last case is already handled, except for the variation where the materials exist but aren't reachable.

**Comment by Geoffrotism** [comment]
Sorry if I wasn't clear. I wanted to make sure all cases were listed in one place. Will add the scenario of materials being available but untraceable, that's a good catch.

**Comment by koosemose** [comment]
Just wanted to make sure you were aware of it, so it didn't end up doubled up on. 

One other situation that I'm not entirely sure if it should be handled in this or separately is when a character is holding what a job already needs, such as when happens on game load, though I'm not certain if that can happen in any circumstance other than a game load, so perhaps that won't need to be seen to other than properly saving/loading jobs.

**Comment by Geoffrotism** [comment]
Another good one. i don't know how stockpile jobs work, but to build on your point, should a character that has enough materials for a job but it currently trying to take those materials to a stockpile get interrupted into using that new job? It would be more of an optimization then something we NEED to do, but I wanted to hear your thoughts.

**Comment by koosemose** [comment]
I don't think so. In my opinion it would be premature, as when we expand the job system to have more than just high, low, and normal priorities (per character priorities and such) the situations where a character already has a stockpile job but would want to take another job in its place would be minimal.

Additionally it seems that it would cause excessive checks unnecessarily as in most cases it won't be proper, since if a character doesn't have enough inventory, we probably don't want them to try and start the job (and end up effectively reserving the materials for a job that still doesn't have enough and if the materials don't already exist will keep from being used for a job that might be able to be completed, and if they have too much they're going to either have to drop some of them (which I would consider undesirable), or deliver what they have and then still go to a stockpile to deliver the rest. 

I think once we get a more complex job system + less placeholdery materials required for building, the situation where you have precisely what is needed for a job and actually want to interrupt the stockpile job will be very rare if ever.
