### ISSUE TITLE
4fps "Yep, something is wrong with your temperature: Infinity/NaN."

### ISSUE THREAD

**Issue by Jaytheway** [TeamPorcupine/ProjectPorcupine#1541]
At some point during run-time game throws a trillion of Debug.Logs "Yep, something is wrong with your temperature: **Infinity**." Alternating with some amount of  "Yep, something is wrong with your temperature: **NaN**." And then only the **NaN** ones. FPS drops as expected.

Not sure if it's a bug, or just not fully implemented temperature system.

![untitled](https://cloud.githubusercontent.com/assets/22476284/19416436/de142e0c-9398-11e6-8b4c-1b9962893897.png)
...I placed heater after it happened.

**Comment by koosemose** [comment]
If you can figure out what series of steps leads to this, it would be much easier to track down.

**Comment by Jaytheway** [comment]
Got it again: 

1. I started building a platform out of floor tiles to expand the room. 

2. Then I assigned to build a wall to enclose this platform so I could then merge it with the main room. 

3. Before new addition to the room was enclosed, I exposed main room to this platform an so space.

4. Then I finished the wall, so the new big room calculated with the O2 and N2 pressure == 0 and rising slowly. And that's when it started throwing temperature:Infinity/NaN

![untitled2](https://cloud.githubusercontent.com/assets/22476284/19417048/e79282dc-93aa-11e6-9054-5a543b494ae0.png)

**Comment by koosemose** [comment]
Assuming you're on latest master, there's something else you're doing that affects the appearance of this bug, I've followed your steps several times, both in and out of dev mode, and can not recreate.

**Comment by Jaytheway** [comment]
It seems so random. I could get it ones more, but I'm not sure how.  I know almost for sure that every time it happens O2 to N2 is not 50% to 50%. 

Also there is another bug. When trying to put a stockpile in an unreachable place it throws out a billion of `...abandoned their job.` messages. It also happened when my stockpile was full, there was resources on the ground and I placed a new stockpile. But this time it wasn't so bad as when the stockpile job was in unreachable room. 
![untitled](https://cloud.githubusercontent.com/assets/22476284/19420268/4a9a9514-93f0-11e6-9510-f29e88fad151.png)

**Comment by Jaytheway** [comment]
I shall create a separate issue for stockpile bug.

**Comment by koosemose** [comment]
And there's another bug, the o2 gen shouldn't be pumping out 50% 50% blend, it should be pumping it 80/20.

**Comment by dusho** [comment]
about that temperature bug, I still wasn't able to reproduce it. Code in question is LUA:
```lua
tile = furniture.tile
    pressure = tile.Room.GetGasPressure() / tile.Room.TileCount
    efficiency = ModUtils.Clamp01(pressure / furniture.Parameters["pressure_threshold"].ToFloat())
    temperatureChangePerSecond = furniture.Parameters["base_heating"].ToFloat() * efficiency
    temperatureChange = temperatureChangePerSecond * deltaTime

    World.Current.temperature.ChangeTemperature(tile.X, tile.Y, tile.Z, temperatureChange)
```
There I suspect tile.Room.TileCount being zero (something to do with outside room?), causing pressure and efficiency to get NaN (clamp01 of NaN still gives NaN, PositiveInfinity and Negative are clamped ok.
This formula is duplicated in RTG and Heater update.
I think checking tile.Room.TileCount for zero (pressure should be 0 then too) should fix the problem - but again, can't reproduce, can't test..

**Comment by Geoffrotism** [comment]
I am almost 100% certain that the problem as to do with tiles heating up above the temperature of the heat source (should not occur). If you want to assign the bug to me, I also want to change the overlay values. It is currently in Kelvin, but would like to add an option to have it in Fahrenheit or Celsius.

**Comment by koosemose** [comment]
We can't assign bugs to non-collaborators (Gatekeepers), but stating you plan on taking a look at it should be enough. If possible try to do the fix to the issue separate from changing the values. But for the purposes of the overlay what the actual measurement is in doesn't matter only that it's on an appropriate scale to provide the needed numbers. I would advise looking to add mouseover info showing the temperature in a more common temperature scale (perhaps with a setting to choose between celsius, kelvin, and fahrenheit, or at least celsius and fahrenheit)

**Comment by Geoffrotism** [comment]
Sounds great.

> But for the purposes of the overlay what the actual measurement is in doesn't matter only that it's on an appropriate scale to provide the needed numbers.

It only goes up to 254 which isnt nearly high enough since it is in kelvin currently. 

>  I would advise looking to add mouseover info showing the temperature in a more common temperature scale (perhaps with a setting to choose between celsius, kelvin, and fahrenheit, or at least celsius and fahrenheit)

If you are in the temperature overlay, it shows the value for temperature of the tile under the mouse. Is this what you are wanting or is is something else?

**Comment by koosemose** [comment]
The overlay should handle converting the output of getTemperature (or whatever the function) to an appropriate scale. The problem of course is that temperature can be a very wide range but only some of it useful. For the sake of discussion, let's say we consider useful temperatures to be from water freezing to water boiling (we probably want a bit more room beyond that, but it eases the discussion if we have simple benchmarks). So the overlay would subtract 273 (prevent from being lower than 0, this gets our baseline at 0), then divide by 373 (put it on a scale of 0..1 between those two points) and multiply by 255 (the range of colors available for the colormap used by overlay)

Of course using water freezing and boiling points for the example makes it so it could be done in less steps, but I'm assuming the overlay will want to show a slightly wider range. Basically temperatureValueAt should return a number from 0 to 255, with the lowest "useful" temp being 0, and the highest "useful" temp being 255, by way of converting it to a value of 0..1 and multiplying by 255. 

And the value shown for mouseover isn't exactly the value in kelvin degrees, it's the value from 0..255 that has been generated by that tile, it will show something in that range for any overlay, it may be that the current implementation naively just uses the kelvin directly and just caps it beyond 254.

But what I'm talking about is, regardless of what temperature scale the temperature actually tracks in (potentially useful to continue doing so in kelvin, due to the formulas used expecting to use kelvin), in the mouseover info that currently shows TileType, Room Index, and Gas pressure, also showing the temperature in one of the more commonly understood temperature scales (with a possible option to leave it in kelvin for those who want to get extra science geeky about their game)
