### ISSUE TITLE
Definition Documentation

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1548]
_Changes implemented from Discord and Comments_
### Expected behavior
- A definition wiki with every function name, 
### Specs
- Every class would be a heading that shows where it inherits.
  - Every function would be put in C# format; e.g.
    - `public Int Foo (String parameterOne, Float defaultedParameterTwo = 0)` 
  - As well as Lua (If it can be called from LUA); e.g. 
    - `function getbinhandler (parameterOne, defaultedParameterTwo)`
      - `--parameterOne: String, defaultedParameterTwo: Float = 10; Returning Int`
- Every class, function, parameter so on would have a summary (we currently already have this, in the internal documentation)
- We would use a documentation tool (currently having a look and will report findings at the end of today) that we will run before every milestone (since milestones will be the 'distributed' version and that's the version modders will use).
  - Any tools that auto-generate the documentation that you guys have used in the past just comment below!

**Comment by frankitox16** [comment]
I agree that the wiki is a bit outdated, but I don't quite remember if the "How it works" section was specific for modding and the code had to be commented to give some sort of summary of what it did. This way we keep what's c# specific to itself, and have that section for modders.

**Comment by BraedonWooding** [comment]
Yes, but its not just modders that will code in LUA since the core game objects will have to be written in LUA?  This way it could then be pushed over to a website later for modders or wherever?

**Comment by frankitox16** [comment]
No, not just LUA. As stated in a comment in #1465 C# modding might be implemented in either this or the next milestone. However, modding itself isn't fully implemented, therefore lots of changes are being done to many of our prototypes, and making a full wiki of this might lead to some misunderstandings if it happens to be outdated.
I do agree that some sort of idea of how things work should be specified in some section of the wiki, in order to help anyone who wants to contribute with some code, or have a starting point to contribute with this project.
Anyway, if you have a specific cuestion, try to ask in the [discord channel](https://discord.gg/68hkpSA), there're plenty of users online willing to help.

**Comment by BraedonWooding** [comment]
Anyways the point of the wiki would be to update it since if things are going to be outdated we need a source of information that isn't so people who are dealing with the newly coded sections understand the definitions (what they can and can't do)?  Otherwise you spend hours looking at definitions (slight exaggeration sure), I was more indicating at a definition wiki rather than a 'how things work' to indicate what parameters and so on functions have.  This is often used (a lot) since it prevents people (somewhat at least) from circumnavigating modules and encourages modulation, since you are only meant to call the functions within a class (if you have physics needs go to the physics module and call the specific function/ if you have sound needs call the sound module).

**Comment by bjubes** [comment]
removing ongoing tag as its for todo lists that track large, partially implemented features.

I totally agree on having a tool that converts in code docs to a more formal documentation. This could even be potentially run by travis/chron job to update automatically even more often than per milestone (assuming there is separate stable and dev documentation). I would also want to ensure it could be added to in some way so that its possible to give in depth explanations without putting a 25 line comment in the source.

**Comment by BraedonWooding** [comment]
Yep!  I agree

**Comment by bjubes** [comment]
I looked at one option, doxygen. I left everything as default in their setup and pushed the resulting docs here: https://bjubes.github.io/ProjectPorcupine/html/.
Its well....not pretty... but it does grab all the info docs should have and even has a working search bar and inheritance diagrams despite being plain HTML

**Comment by BraedonWooding** [comment]
I'm looking at a few others but I actually quite like that one, sure it ain't too pretty but it is feature heavy.

**Comment by bjubes** [comment]
actually it supports html headers and footers as well as custom css, so someone will make it pretty eventually.

**Comment by BraedonWooding** [comment]
Damn yeh, okay so I think we should go with this!  Should we setup a page for the documentation?

**Comment by bjubes** [comment]
no not yet. we still need to make sure no one finds a better option and explore doxygen more in depth to make sure its the right choice. Also we need significant (positive) feedback to make a legitimate addition to the project.

**Comment by frankitox16** [comment]
I'm not aware of other tools for code documentation, however, I could make the CSS for that doc and make it preety :smile:

**Comment by BraedonWooding** [comment]
Closing since no conclusion was reached, sandcastle and doxygen are two possible solutions.
