### ISSUE TITLE
[pull request made] [enhancement] FPS Counter Additions

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1550]
*Currently I'm implementing this.  PR hasn't been made* **yet**
### Expected behavior

- An average FPS (for last 30 seconds)
- A min FPS (the lowest FPS reached)
- A max FPS (the highest FPS reached)
- Current ms (will be 0 till we add networking)
- Total Memory, Allocated Memory and Memory for Mono

Something that looks like:
![image](https://cloud.githubusercontent.com/assets/22880786/19430725/253dce56-94a1-11e6-9fa8-11b408b4af2f.png)

### Actual behavior

Displays the current Frames per Second (FPS)

**Comment by frankitox16** [comment]
This is more of a debug screen, and should be implemented apart from the fps counter. I think that this kind of info is slightly more convenient when we focus gameplay and the bugfixing becomes harder (eg: when it's a specific problem with an OS and a bugtracker sends those issues)

**Comment by mlwooding** [comment]
We could always have multiple variants? Like basic (just fps), standard (avg fps, and ms), and two more one for all features bar graph the other for graph as well?

**Comment by BraedonWooding** [comment]
We could always have multiple variants? Like basic (just fps), standard (avg fps, and ms), and two more one for all features bar graph the other for graph as well?

**Comment by frankitox16** [comment]
Yes, this would be OK, my point was that as this isn't exactly a full release and current bugs come from scripting instead of PC performance, so having this information CURRENTLY won't make much difference. When this project gets distributed (that is, in later stages of the project), bugs may appear from PC performance, and that's when this kind of information could be useful (maybe if we try some sort of benchmarking?). 
If you want to try to make it and do a Pull Request, it's great, the the sooner, the better, This kind of ideas are great for the project. If there's any help you need, feel free to ask.
PS: This is just a personal opinion. Maybe someone will come with a good reason why we could need this sooner, but I personally think this isn't a priority right now.

**Comment by BraedonWooding** [comment]
Yep :D, I just thought that since I have a bunch of time spare and I know C# and Unity really quite well (4+ years so far) then it would be a good way to learn more about the project and its systems.  I'll do a pull request and give it a whirl :D.

**Comment by koosemose** [comment]
Just please be sure to make all the extra stuff able to be not shown, separately from fps, I'd rather not have all the extra crud in the way if I'm just trying to keep a rough eye on FPS.

**Comment by BraedonWooding** [comment]
Yep that's what the different modes will act as.  I'll do some presets first (basic-fps, standard-fps+ms, extensive-fps,min/max/avg,ms, verbose-all) but maybe later implement a custom that allows you to tick on/off certain aspects.

**Comment by koosemose** [comment]
I'm very wary of any sort of running log of fps... o.O

**Comment by koosemose** [comment]
Any kind of regular log (particularly if it's writing to a file) will slow things down noticably.

**Comment by BraedonWooding** [comment]
Okay, so no log.
