### ISSUE TITLE
[enhancement] Middle Click Center view

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1551]
### Expected behavior

Middle clicking should center the view on the cursor (this is standard behaviour in a lot of top down games), dragging would just be the same as right click.

### Actual behavior

Nothing

### Specs

Middle clicking (not dragging) would center the view on the cursor.

**Comment by koosemose** [comment]
For me, at least, it seems this would lead to more annoyance than usefulness, completely losing my place in the world from an accidental finger twitch while trying to pan around the world seems like it would happen much more often than I would want to specifically center my view (especially since, in the future, when the player has more control over the location of their base, the base may well not even be in the center, in which case it only manages to take you to an empty area of space.

Of course, if we implement actually being able to set what keys do what (and hopefully mouse buttons as well), my argument becomes moot, as I could either unset it for myself, or if it's not default then one could set it to that.

I will note that you can set predefined camera views (I think ctrl+F1-F4) and go to them with F1-F4, which would accomplish a similar goal (and with rebindable keys + mouse (maybe not standard clicks?) one could bind middle mouse to whatever camera view your base is at.

**Comment by BraedonWooding** [comment]
Yep, okay I'll close it for now?

**Comment by koosemose** [comment]
Don't feel you have to close this just because I've disagreed with you, for all either of us know everyone involved in the project may come in over the next day and disagree with me... or someone will get froggy and implement the key+mousebinding setting that could give us both what we want. :) 

Unless of course you feel the current "setting a camera view" thing satisfies the need, but it's up to you, either way.

**Comment by BraedonWooding** [comment]
Well if we are keeping to a informative issue stance than wouldn't creating a new issue about having predefined camera views be preferred?
