### ISSUE TITLE
Claiming Inventory

### ISSUE THREAD

**Issue by Geoffrotism** [TeamPorcupine/ProjectPorcupine#1610]
We need some way for inventory to be claimed. Currently multiple characters will all go to the same inventory for different jobs. There's no need for everyone to bum rush the inventory. Once one character decides they need that for a job, let them claim it so no one else can use it.

Steps to recreate -

1. Have more than one character.
2. Spawn in some inventory.
3. Watch the Black Friday rush.

**Comment by BraedonWooding** [comment]
I can include this as I delegate jobs, since I want it so you can just ask the jobManager to find inventory of type x (essentially what it does right now), but this really should be a seperate PR flag that way I'm just mainly interfacing with a job manager rather than also interacting with inventory and other stuff. So to recap this should be a seperate PR that my jobManager could interface with.

**Comment by dusho** [comment]
so there will be flag reserved on inventory and it will be set on first FindInventory call, and then FindInventory will skip reserved items? 
I can feel that there will be issues with un-reserving the inventory (when job is cancelled, when character dies, etc)

**Comment by Geoffrotism** [comment]
Why would that be an issue? Those are situations in which you would set the flag back to unreserved for sure. Is there a better way to handle this?

**Comment by bjubes** [comment]
I think job manager or some other class should hold the flags, not the individual furniture.

**Comment by Geoffrotism** [comment]
This was for inventory, not furniture. Not sure if that changes your opinion.

**Comment by dusho** [comment]
yes. JobManager should hold that info, as it will be main place to track if characters job needs inventory..

**Comment by Geoffrotism** [comment]
I can't think of how that would be done efficiently. Would either of you mind explaining to me how that would generally work?

**Comment by koosemose** [comment]
If it's on a manager class, it makes more sense to do it from InventoryManager, since that class is the one that handles inventory. That way if anything else needs to be concerned about inventory being claimed, the information can be gotten from a logical place. Plus it makes it a lot easier to get a list of non-claimed inventory, just by having a Where (or similar) function check that it isn't claimed, rather than having to get a list of claimed inventory from JobManager, and then passing that list to InventoryManager, which then has to check that each inventory item isn't in that list, or some other awkward means of passing the information along of what inventory isn't wanted.

Of course I also think it makes the most sense for it to be a field/property of a specific Inventory, since it is information about that specific inventory, and it allows a much simpler check for non-claimed inventory (`.Where(inv => inv.claimed == false` instead of something along the lines of `.Where(inv => !ClaimedInventory.Contains(inv)`, which, if I understand how `.Where()` is implemented would basically be doing the equivalent of a foreach loop through the ClaimedInventory container for ever inventory being checked, rather than just checking a field/property of the specific inventory)

**Comment by BraedonWooding** [comment]
Yep I 100% agree, otherwise it has weird occurrences with Inventories being deleted and it's kind of isolated from the inventory in question.

**Comment by koosemose** [comment]
A basic inventory claiming system has been implemented.
