### ISSUE TITLE
[Discussion] Clean up Tile

### ISSUE THREAD

**Issue by crazyfox55** [TeamPorcupine/ProjectPorcupine#1633]
The Tile implements IComparable and IEquatable, but this code is never consumed. I also don't see a reason to implement these interfaces. Should this code be removed?

**Comment by BraedonWooding** [comment]
It doesn't really affect any code, and it may be needed later.  Also I believe it does get used (Tile == Tile), at one point, that may have been removed however.

**Comment by crazyfox55** [comment]
I don't think there would ever be a case where some class/method would have a Tile "t1" and Tile "t2" where the fields/properties of "t1" equals "t2" but the references of "t1" and "t2" are not equal. Therefore the [default ==](https://msdn.microsoft.com/en-us/library/53k8ybth.aspx) which compares references would work fine.

**Comment by BraedonWooding** [comment]
True, well I don't know much about the Tile code, @koosemose do you know if Equatable or Comparable is used much in respect to Tiles?

**Comment by koosemose** [comment]
Well Comparable affects the sort order of tiles, and I'd prefer to have the sort order defined in a reasonable manner, rather than whatever the default might be.

The heaviest use of Tile.Equals is in pathfinding code and related things, I'm not entirely sure how/if removing Equals would affect that.

@vogonistic care to comment, the it seems almost exclusively your code in pathfinding that makes use of it.

**Comment by crazyfox55** [comment]
Good point on comparable affecting sorting. That is much harder to track down with reflection. I'll try to take a closers look and see if I can find any current sorting. 

Even if there is no use of the comparable interface  currently, I think it should be left in for use if future sorting problems.

As for IEquatable, I'm still not convinced.

**Comment by crazyfox55** [comment]
Closing because I see this a low priority at best.
