### ISSUE TITLE
[Disscussion] Remove List<Character> From Tile

### ISSUE THREAD

**Issue by crazyfox55** [TeamPorcupine/ProjectPorcupine#1635]
Current Implementation:
Each Tile has a list of characters that are currently standing in them.
Each Character removes itself from the list when moving off a tile.
Each Character adds itself to the list of the next tile.
The List is only accessed after a user clicks the makes a selection or contextual action.
The List is loaded into other data structures.

Looking at the code references that use the list of characters tile manages:
1. void BuildStuffInTile()
        - re-allocates and fills an private list for flipping through a selected tile
        - uses a Tile Property to grab the items associated with the selected tile
2. List<IContextActionProvider> GetContextualActionProviderOnTile(Tile tile)
        - returns a brand new List that will be used to display a mini menu under mouse 
        - uses a Tile parameter to grab all IContextActionProviders within the selected tile

The Issues:
1. For most of the tiles and most of the time the list will be empty
2. Every move of every character requires adds and removes from a list
3. The list is valuable for only one tile when a user clicks (very infrequent use)

The Benefits of change:
1. Reduce the responsibilities of the character class (i.e doesn't manage list)
2. Reduce references to empty lists (memory benefit)
3. List isn't updated on every character move (cpu benefit)
4. consolidate character management to the CharacterManager class

Proposal:
Add method to the CharacterManager that takes a tile as a parameter and returns a list of characters. 

Method 1:
CharacterManager looks through each character and grabs those with the given tile

In addition a HashSet<Tile> could be added to CharacterManager that tracks all tiles with characters in them. The benifit would be faster list character list generation for tiles without characters. The cost would be each character would need to update the HashSet for every tile movement.

If you think these are good reasons please respond with your ideas/opinion.
If you think the additional Hash Set is not necessary please comment.

Thank you,

**Comment by BraedonWooding** [comment]
Its a good idea, the only problem I can think of (right now) is the method to get list of characters for a tile, cause is a linq.where statement (with a lookup) faster then just getting a list.  I like the hash set (though I would suggest a dictionary be preferred since then you could just do [Tile] to get a list of characters, rather than having to do a search).  However, in either way a character still adding itself to the collection.  Collection types are relatively space efficient, so its more speed related since if you right click we want 'instant' reaction menu.  However, I do like your proposal to move it away from the tiles, since I agree its not good to have it on the tiles since its not scalable.

**Comment by koosemose** [comment]
Removing this solely for the sake of efficiency is premature optimization, any effect on performance tracking a list of where characters are is negligible. As far as rather or not we really need to have each tile keep track of which characters are on it, right now, probably not. However, we are still in a state of not having many of our base functionality in place, and I'd rather not have something removed that's not currently causing a problem, to only have to have it reimplemented later for some other feature to use.

A Dictionary, as @BraedonWooding suggested might work better (perhaps each entry containing a list of all characters on that tile), though of course without maintenance that's going to fairly quickly grow out of hand, and I'm not sure if having to do additional maintenance cause it to not be any benefit in the end.

Specifically on the subject of selecting a character however, in general, the current method of basing it on the tile the character is "in" isn't that great. You can really see the deficiencies if you try to select a character who is moving, until they are fully in a new tile, you have to click in the tile they are leaving, which at some points in their movement the sprite won't be overlapping at all. It would be better if we could build the list of selectables in two stages, one as it is now (minus characters), and another that does something (maybe a raycast?) so that it's actually clicking on the character that adds it to the list.

**Comment by crazyfox55** [comment]
I agree that the performance is negligible, however I could imagine a game space that is 1000x1000 tiles but I couldn't imagine having more than 200 characters. 
With that in mind the time necessary to compute a list of characters for any given tile would be 200.  While the current method would be 1. 
This makes it seem like the current method would be fine but there are hidden costs. The hidden costs of managing every tile movement at all times of 200 characters.
Besides performance, because it's not that important now, I still think the character shouldn't be maintaining a list on a tile. The tile could still have a list of characters property but it would reach out to the character manager for the list.

Now back to performance, I think a dictionary could make it worse. Currently the lists are initialized and ready to go on the tiles, but in a dictionary lists would have to keep getting remade every time a character changed tiles. Or use some pool of lists that the character manager could put in. 

The benefit of a hashset are similar to a dictionary  but a search is still needed if the hashset contains the tile. Once again searching 200 characters is quite fast.

I agree selecting a character is going to change and very likely get pushed to the responsibility of the character sprite controller.

**Comment by crazyfox55** [comment]
Check out my commit to see/test the changes I proposed.
https://github.com/crazyfox55/ProjectPorcupine/commit/123d90eb6c4ba9de11c8f38934da82c1e86cace1

**Comment by BraedonWooding** [comment]
@koosemose I would say close unless @crazyfox55 wants to open a PR?  I personally dislike removing it and as I said before a dictionary is my personal preference.
