### ISSUE TITLE
Wiki Github Code Examples

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1646]
I'm just making this issue, since for some reason I didn't need to make a pull to edit the wiki, so I thought I might as well put them here, to double check they work for everyone (they work for me), and that they actually made it to the wiki.

```
# Fetch upstream then merge into current branch
function gitMerge () 
{
	git fetch upstream master
	git merge upstream/master
}

# Add Files, Commit, then push to current branch
# Call Like gitDone "Commit Message"
function gitDone () 
{
	git commit -m "$1"
	git push
}

# Add all code files (this should avoid weird commits)
function gitAddCode () 
{
	git add *.cs
	git add *.lua
}
```

Weird issue I know.

**Comment by bjubes** [comment]
ins't gitMerge identical to just pulling from upstream/master?

**Comment by BraedonWooding** [comment]
True, I guess though this way you don't need to type the upstream master.

**Comment by hcorion** [comment]
IMO it's actually better to add files manually, because then you don't get commits like this: https://github.com/TeamPorcupine/ProjectPorcupine/pull/1569/commits/35c45941709dee84fcdd5f3fe169fc47cf895440 😛 .
And the wiki is just like any other wiki (ie Wikipedia) pretty much anybody can edit it (I think you have to have a github account though), that's why you don't need to make a PR.

**Comment by hcorion** [comment]
I'm also finding the `gitk` and `git status` commands very helpful.

**Comment by BraedonWooding** [comment]
Hehe true, I'll actually remove that.  Gitk & git status are actually pretty amazing.  If you have any common commands that you use together suggest them too.  Just this way we have a little bit of a record.

**Comment by BraedonWooding** [comment]
Closing cause feedback positive of changes, and really this was just a way of having a record.
