### ISSUE TITLE
[Question] How do i import my Forkes and Cloned repo into Unity? [Question]

### ISSUE THREAD

**Issue by kingcraftingnl** [TeamPorcupine/ProjectPorcupine#1648]
How do i import my Forkes and Cloned repo into Unity?

**Comment by UnknownSoldier1** [comment]
If you already have the project on your pc (I just assume that since you said that you have cloned it), you just open Unity. When you have done that and Unity asks you for the project you want to open (if it doesn't, click "File->Open Project..." in the editor) and then press open. Then you'll get a file search dialog. There you simply select the cloned folder. Done.

**Comment by hcorion** [comment]
In the future you should ask these sort of questions on discord https://discordapp.com/invite/68hkpSA or the official subreddit: https://reddit.com/r/ProjectPorcupine

**Comment by koosemose** [comment]
Here or Discord are proper places. The "official" subreddit isn't really that official and isn't heavily frequented.

**Comment by hcorion** [comment]
So shouldn't we change the unofficial discord to official then?

**Comment by frankitox16** [comment]
If you're trying to open just the scene, there's a folder inside the Assets called "_Scenes_". There you'll find the scenes that you're looking for.

**Comment by koosemose** [comment]
@hcorion The Discord isn't really official either, but it's still useful since it can get a quicker response time (sometimes)... more accurately the subreddit really shouldn't be listed as official.

**Comment by BraedonWooding** [comment]
If your question has been answered close the issue :D

**Comment by koosemose** [comment]
Closing as Resolved
