### ISSUE TITLE
Add branch with stable builds

### ISSUE THREAD

**Issue by Dan54** [TeamPorcupine/ProjectPorcupine#1711]
We should add branches with windows, OS-X and Linux builds of the current [`stable`](https://github.com/TeamPorcupine/ProjectPorcupine/tree/stable) branch for people who want to play without installing unity.

**Comment by BraedonWooding** [comment]
That's not how you do it with github, otherwise it would get very messy (and annoying to update them).  The master branch is the Unity file which is universal across all platforms, and would require you to own unity to play (but that is 'stable' meaning that bugs may fall through the cracks and so on).  At every milestone (0.2 is coming up soon), we will add a 'release' which you can see on the main page under releases currently 0.1 and 0.1-Alpha exist, they are very old but we don't really want to constantly add versions, but the whole point of releases is to be the most stable versions that exist :D.  If we had branches it would require a lot of work every time a release is done.  Also the game is mostly just prototyped and isn't balanced at all (requiring you to cheat items in to even be able to play), since we wanted to get the main features done before we started balancing things :D.
