### ISSUE TITLE
Mod Selector and Saving

### ISSUE THREAD

**Issue by Dan54** [TeamPorcupine/ProjectPorcupine#1713]
I'm working on a mod selector, are these good features?
* Selection menu
* JSON mod data
* ~image~, title and description
* active mods saved in save file and settings
* ~`graphical` setting makes mod not get saved with save file and load after other mods~
* Load order editable in mod selection menu
* `doNotSave` bool makes mod not be included in save

**Comment by hcorion** [comment]
+1 for json.

**Comment by BraedonWooding** [comment]
Sounds great :D.  With the whole UI, maybe add a photo of a rough (could even be a google image) idea of what you are aiming towards :D.  Also love the idea of active mods but with the 'settings' part we already have a settings menu, so don't worry about the settings for mods since that handles it already (makes your life easier :P).  What do you mean by the 'graphical' setting?  Like its just art and graphics?  Oooh one other thing that I just thought of maybe make it so you can re-order them in the selection menu, and that order is the order they are loaded in ?  Or is that what the graphical setting is for?

**Comment by koosemose** [comment]
Just to add in some relevant things that have been discussed in the past: It's intended that the core data files be loaded basically as a mod (so a player could disable "core" and have a mod that completely replaces pretty much everything from it), with a lot of the elements discussed in #772. Another thing that has been discussed is having a default directory set up, such that with no special config file a mod will load everything in <Mod Name>/Data/Furniture.xml as Furniture, and so on for each appropriate part. Or at a minimum having a default "sample" config that sets things up as such.

I'm not sure there's a huge need for explicitly marking a mod as "graphical" or not. Loading order doesn't matter for graphics, they are loaded by sprite name, so don't care if the thing they are a graphic for is already created or not. Loading order matters a lot more for code/data based mods (if two mods affect how a door works, the last one would/should override the others), and I suppose load order matters for graphics, but only relative to other graphics (if both replace the wall sprite, the last one loaded would be the one used).

If core is implemented as a mod, we need to ensure it is loaded first (as we want other mods to be able to overwrite aspects of it, rather than have it overwrite aspects of mods). 

The only benefit I can see of marking some mods as graphical is so that they can be used/not used between various runs of a save game, but there are other mods that may be viable for that as well (anything that changes how a thing functions rather than adding new things, for example). Since the mod needs to tell the game what kind of things is being loaded anyways (either through a config file or location), we can just give appropriate warnings when someone enable/disables  (or tries to load a game without a mod that they previously had active) a mod that uses data or code files.

**Comment by BraedonWooding** [comment]
I'll just add that's what I mean by the loading order, ^^ is a lot more clear than what I said lol :P.

**Comment by Dan54** [comment]
I'll replace the `graphical` setting with editable load order and `doNotSave`

**Comment by Dan54** [comment]
Also, the sprite loading system would need too much work to load sprites for the menu, feel free too add image support later.

**Comment by Dan54** [comment]
The menu will look a bit like the Civ V one: (not my picture)
![image](https://cloud.githubusercontent.com/assets/21107149/21451034/d25d9b58-c8f3-11e6-809f-ac35706ad7d3.png)

**Comment by BraedonWooding** [comment]
@koosemose Should probably be closed since it was never implemented and in a pseudo completed state
