### ISSUE TITLE
[Discussion] Fixing Smelters/Smelter tiers

### ISSUE THREAD

**Issue by BraedonWooding** [TeamPorcupine/ProjectPorcupine#1750]
This conversation was had mostly between me, @gunthergun, and @koosemose on discord, I felt it should also be summed up here.

So we felt that a new smelter should be introduced made from asteroid rock, that requires more raw iron and power to produce iron (so less efficient) it only takes up perhaps one square?  This way you can actually make iron...

Then later on you can build a second tier (and perhaps higher tiers) of smelters taking up more room but being more efficient (maybe for the second tier you require iron (in smelted form) and to build some copper circuits at some workshop or whatever.

Koosemose also suggested "a trading console to sell overpriced crappy equipment", which also is a valid way to get it (by selling raw iron to get money to buy either parts for a smelter or the smelter itself).

**Comment by dusho** [comment]
This feels like balancing the game already. I think we are still far from there as I don't think any thought was given to progressing in game (gameplay wise). For now we are just adding basic versions of furniture to hopefully cover all functionalities we need. We still may scrap lots of stuff and then updating several smelters (or versions of other furniture) will be just more work. Even now I feel that some furniture is not used at all and may not function as it was long time ago.

**Comment by BraedonWooding** [comment]
It's more about making it so v0.3 is semi-playable so you can progress and atleast begin to test without using a dev mode or whatever.  It'll help keep interest in the project too which is good in the long run

**Comment by dusho** [comment]
I see.. so we want some survival scenario in 0.3 already. I would love to have that, but last time people didn't even manage to agree on what it would be like, what would be the goal and process of getting there.
Also, gameplay wise.. we need to introduce some space junk (broken furniture or something - similar to slabs in Rimworld) and maybe that use as 'starting' materials for building crappy 1st tier stuff. Building smelter out of rocks inside the spaceship/starbase feels a bit off.. (technologically)

**Comment by koosemose** [comment]
I still think there is some basic functionality we're missing, particularly with the number of things that were missed from 0.2. Though it can be beneficial to start thinking about Progression.

Though I don't think in all cases tech progression should be just a straight upgrade (i.e. perhaps tier 2 smelter isn't simply just a faster smelter, but is a potential trade off, i.e. It may smelt quicker, or more at once, but it requires more power per "smelting operation" Or as is the case as I envision the fission reactor, which I see as a tier 2 fueled generator, a lower tier fueled generator just takes a simple fuel no processing needed, whereas the fission generator requires processing, meaning more infrastructure is needed, but produces more power as a result. And perhaps a 3rd tier fueled generator (such as a fusion reactor perhaps) requires power to start up, but of course produces a tremendous amount of power, so even though a single fusion reactor is likely to handle all of your base's needs, if something causes it to need to be shut down, you still need other power sources to boot it up.

And we already have part of that sort of thing going with the solar panel and RTG, solar panel is big and bulky, but rtgs potentially have some tricky working around their heat generation (plus perhaps being harder to make in the future, such as requiring a waste product from a fission reactor)

**Comment by sboigelot** [comment]
> It's more about making it so v0.3 is semi-playable so you can progress and atleast begin to test without using a dev mod

That would be great; I pull the latest upstream last week trying to get back into the game as I had one hour to see the progress done since I couldn't participate. And... I wasn't able to build any kind of furniture beside stockpiles.

Mining was providing me with raw material but I was not able to build a metal smelter or a mining drone.

As I didn't know this was intended and I had to use the dev console to cheat in material, I just lost time trying to figure out if my code was up to date as nothing was working and the state of the gameplay was worst then a month or two before.

Being able to play the game is a good way for contributor to be involve again and learn, in a few minute the state of the current bugs/issue/features.

> I see.. so we want some survival scenario in 0.3 already. I would love to have that, but last time people didn't even manage to agree on what it would be like, what would be the goal and process of getting there.
Also, gameplay wise.. we need to introduce some space junk (broken furniture or something - similar to slabs in Rimworld) and maybe that use as 'starting' materials for building crappy 1st tier stuff. Building smelter out of rocks inside the spaceship/starbase feels a bit off.. (technologically)

I don't think we need anything fancy or even worry about balance, scenario etc, we just need to be able to start with a stockpile full of basic materials that can't be mine are a required to build the first necessary furniture.

**Comment by BraedonWooding** [comment]
Closing for now since this is really far off and progress is slow so consolidating is better than fixing off things.
