### ISSUE TITLE
Furniture.xml should not have name or description fields.

### ISSUE THREAD

**Issue by svmnotn** [TeamPorcupine/ProjectPorcupine#211]
Now that we have localizations, the "human" and and desc should only be handled in the localization code. No need to also have it on the xml.

**Comment by vogonistic** [comment]
I'm not sure about this. It would require a change to the localization so it falls back to a default, like `en_US`, if there is a missing translation. It's very hard to keep all localizations complete, and we need something better than the key instead of a description of missing items.

I think having the fallback name and description in the xml is a pretty good way to guarantee that there is always something to display. Another benefit is that when you edit a longer xml, you can also see what the object is and have plenty of things to search for.

**Comment by svmnotn** [comment]
I need to check the localization code again, but from what I saw the first time that ability should be there. Also it can always fall back to the key being used like in many games (looking at Paradox here...). This is just because currently the XML and the en_US.lang file have to be kept "Up to date". It would be much better if only one of them had to be changed whenever a new item was added.

**Comment by svmnotn** [comment]
I just checked and by default the code will return the English version and if there isn't one it will return the key

**Comment by vogonistic** [comment]
I haven't checked what it does since yesterday, but returning the key is probably not a very good replacement for description unless we start using the full descriptions as the key.

The reason I think it's good to keep in Furniture.xml is that you must change that file to add something new. Having to also change en_US.lang is an external dependency. The requirement will probably be found pretty fast if we show the keys, but I don't think it simplifies anything to remove it from Furniture.xml.

I think I'm arguing that the en_US.lang file  is what shouldn't exist if that is our default language.

**Comment by bjubes** [comment]
Also keep in mind that if a modder ads a custom furniture it should be able to display it's name properly even if it has no localizations

**Comment by svmnotn** [comment]
Ok after looking at the code I'm closing this pr in favor of a different one adressing all the places where name, and desc are used so that we can switch and use those as the localization tags.

But first a response to the comments:

@vogonistic you are right it shouldn't if that is the default but I think that the better option is leaving it up to the modder on whether that want to opt into the translation or not. 
Thus making this my next point: 
- Remove the `LocalizationCode` and `UnlocalizedDescription` from the xml and simply use the `Name` and `Description` as the key.
This would mean that if the modder does not want to add localization then they could just not edit the lang files, since the name and desc are used as the keys if they are not localized then there is no issue. Which also addresses @bjubes point of allowing modders to no localize things.

**Comment by vogonistic** [comment]
I think your last point is a good solution.

**Comment by svmnotn** [comment]
@vogonistic look at #216 for the full ... well I'll call it an RFC
