### ISSUE TITLE
Discussion: English/Canadian spelling VS. American spelling

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#223]
Opinions? 

Specifically, and example of this would be something like ["neighbour vs. neighbor"](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Models/Tile.cs#L221), where technically "neighbor" is the "correct" spelling according to most dictionaries, but "neighbour" is accepted in the UK and Canada.

**Comment by ComputerOverlord** [comment]
Quill's Canadian. However localisation says "en_US"

**Comment by WardBenjamin** [comment]
Exactly, which is why I bring it up. We could also add "en_GB" for UK spellings and "en_CA" for Canadian spellings, so that's an option.

**Comment by Dormanil** [comment]
Do I sense a certain US bias? Dropped 'u's and similar things are _only_ in American English. 

Nonetheless, in code I'd vote for "use whatever version of English you want, as long as it's correct", while the localized names for display in-game should default to `en_US`.

**Comment by Dormanil** [comment]
And some fine person already had a pull request for `en_GB` earlier, I would not be surprised if `en_AU`, and of course `en_CA` appear sometime soon.

**Comment by brlodi** [comment]
> in code I'd vote for "use whatever version of English you want, as long as it's correct"

@Dormanil I'd actually argue against that on a number of bases, primarily consistency. We don't want some variables to be "steelColor" and others "woodColour", both for searching purposes and just general niceness. We should standardize on one, and while frankly I wouldn't care in a purely human-readable scenario whether to use the American or UK spelling (I'm American but personally think the UK spelling looks nicer), Unity and C# resemble most programming languages in using US English spelling. Therefore, for the sake of consistency with in the project code and to better match the Unity frameworks, I propose we define US English as the standard for code.

**Comment by brlodi** [comment]
I'm all for localizing user-facing elements to any version of English deemed relevant, of course.

**Comment by quill18** [comment]
Unity (and many other language/libraries including HTML/CSS) use US spelling (e.g. Color) and I'm fine with standardizing on that in code.

I also wouldn't personally bother with more than one English localization (most likely en_US), but if people want to spend their time maintaining more than one, they're free to do so.

**Comment by Dormanil** [comment]
To be entirely correct, Unity and C# (mostly Unity), are inconsistent about that as well. Heck, there are "Color"s, but every Unity script per default extends **MonoBehaviour** with that nice little u in it. 
100% consistency will be impossible, now I'd just go with the way that needs the least amount of refactoring. And since Quill wrote most of his code the UK way already, I'd propose we define UK English as the code standard.

**Comment by brlodi** [comment]
@Dormanil I have read that line I don't know how many times, and honestly never noticed it was "behaviour" 😣

**Comment by brlodi** [comment]
I would argue, however, that US English is still more prominent in Unity than the UK spelling, and a cursory search of the code shows 5-6 uses of "neighbour" as the only examples in @quill18's code. I don't think that's a noteworthy amount of refactoring at this stage.

All this said, though, I'm not going to argue viciously in favor of my country's rather silly spelling deviations if the community would prefer UK English. I do think we should decide on a standard sooner rather than later.

**Comment by Dormanil** [comment]
Well, in the end, whatever variant of English we will choose is irrelevant, as long as we don't suddenly decide to switch _again._ If I get the correct sense of our current developer base, people do accept en_US as the default locale. And since I seem to be the only actual proponent of en_GB as the coding language, I bow to the will of the community and code from now on in defense values, armor ratings and neighbor tiles.

**Comment by mikejbrown** [comment]
Is this still an issue?

**Comment by WardBenjamin** [comment]
Nope, closing! 

Thanks for going through these issues @mikejbrown!

**Comment by aafreenart** [comment]
What is the best way to detect the text is en_US/en_GB??
