### ISSUE TITLE
Finalise the move from name to objectType and displayed localisedName

### ISSUE THREAD

**Issue by Dormanil** [TeamPorcupine/ProjectPorcupine#25]
As quill often said, we should probably have objectTypes like "furn_steelWall" and separate displayed names for these objects (in this case "Steel Wall"), maybe even with possible localisation dictionaries that get read from XML. Quill himself partly began that effort with the steel walls when he moved from C# to XML/Lua for the furniture and their custom code.

The earlier we do this switch, the less refactoring is necessary when we actually do this, so I'd personally do that before we add any more new furniture or inventory types.

**Comment by Sommerbo** [comment]
Agreed and support for different languages is also easier the sooner it is done. I maintained a website using three different languages and it was a mess because it was an after thought.
Additionally translations are a great way to contribute for novice programmers or even nonprogrammers.

**Comment by frankitox16** [comment]
Should there be a new folder called "Locale" and adding several folders with their respective lang files? which file type would you use? (json, xml, etc)

**Comment by quill18** [comment]
Unless there's a very good reason for it, we should probably try to avoid having too many markup languages in our program and instead standardize on a single one. It doesn't have to be XML, though anything else would mean someone has to volunteer to do a re-write.

**Comment by meisme** [comment]
As a rule I prefer the simplicity of JSON. With JSON you don't have the same distinction between storing something as an attribute versus a value, and since you can think of JSON as a nested dictionary I find that makes it conceptually easier to work with than the tree-structure of XML.

However the original reason Quill chose to go with XML was to avoid introducing an external dependency, and while Unity does have a JSON-serializer built in, as far as I can tell it only supports serializing to and from classes, it doesn't support accessing the elements of the JSON document arbitrarily. If that serializer had worked like ie. the one in Python I might have argued for switching to JSON, but as it is I don't think the Unity JSON serializer is a good fit for our use case. At any rate it's certainly not a drop-in replacement.

Since staying with XML has the added benefit of Quill's videos on working with XML remaining relevant, I think that might be the best option.

**Comment by koosemose** [comment]
I'd be willing to at least investigate a switch to JSON, and implementing it if I find the JSON-serializer capable of handle Project Porcupine's needs, without adding excess complexity, assuming others find that it may be worthwhile to consider switching if it's feasible.

**Comment by RodRitter** [comment]
I definitely think we should stick to XML considering the whole idea of the project is to be used as a tutorial. Quill has invested a lot of time into the XML serialization aspect. Eventually we could consider an either-or option maybe. But for now I don't think we need to overthink this.

**Comment by NogginBops** [comment]
With localization isn't this fixed?

**Comment by Dormanil** [comment]
_Should_ be. I'll close for now.
