### ISSUE TITLE
New Characters

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#283]
How should we add new characters?

**Comment by Xeni91** [comment]
I think new characters should arrive from the "home" planet after a certain Time or a condition is met.
Like build a living area so that new ppl can arrive. They can help with in base jobs(like crafting fueling the generator) but are unable to walk freely outside of the airlock(missing jetpack or something along those lines)

**Comment by WardBenjamin** [comment]
If we wanted to make it consistent with the story that I came up with in #263, we could find new people through exploration, and find them in their shuttles.

**Comment by vogonistic** [comment]
Drifters & pirates?

**Comment by WardBenjamin** [comment]
Exactly the idea. Pirates would be a cool addition, but implementation of those should probably be discussed in #213. As far as them as a source of new characters, I'm all for it.

**Comment by relinu** [comment]
Improved the eventsystem, now it spawns a new character every 30 seconds (can be changed later to what ever precondition)! #270 :D

**Comment by kd7uiy** [comment]
The respawning periodically is interesting, but in general I think something more deliberate would be best. Either a building or a pre-condition being met.

**Comment by relinu** [comment]
yeah its definitely improvable, if you have a better idea you can change the lua code ^^

**Comment by kd7uiy** [comment]
The cloning pod works well enough for now, I think I'll close this for the time being.
