### ISSUE TITLE
[Bug] Slow performance when travelling far

### ISSUE THREAD

**Issue by RodRitter** [TeamPorcupine/ProjectPorcupine#289]
Hi guys, 

I haven't been following the pathfinding updates but I've noticed a huge hit to FPS when the character tries to go fetch a load of iron plates from a far off place like an asteroid.

**Comment by bjubes** [comment]
Could you include a screen shot of the profiler so we know exactly what is slowing the game down?

**Comment by RodRitter** [comment]
I'm not sure what I need to be looking for exactly but here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/4159679/17816488/aa21c5d2-6639-11e6-8caa-b5d854bdea7d.png)

**Comment by koosemose** [comment]
I'm pretty sure I fixed this (or at least part of it) in PR #250, the issue is that there is a bug in how it determines if the character has a goal that contains the inventory they are looking for, and it fails if there isn't a furniture in that tile, so it looks for a new path (even though it will get the same one), and if it is a far distance the pathfinding is very expensive, it will do this every time the character is on a new tile, and with the terrible performance from pathfinding it will take so long that every (terribly slow) frame is a new tile and therefore new path.

**Comment by RodRitter** [comment]
I removed the Debug.Logs and it seemed to clear it up

**Comment by kd7uiy** [comment]
I'm almost certain that when the mentioned PR gets included (Which you should all ping Quill to get him to do it sooner), this will be resolved.

**Comment by RodRitter** [comment]
Great, will see when he gets on a little later. Closing this now.
