### ISSUE TITLE
Power Generation Localization

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#299]
Okay, so we now have 5 open pull requests that add localization for the power generator.

Can someone go through these (@SanteriHetekivi?) and pull all of the non-duplicate localizations into one pull request?

#169 
#186
#236
#256
#297

**Comment by SanteriHetekivi** [comment]
If creators are okay for me pulling from their PR:s into one I'm all for it, but like i mentioned in #169 I live in Finland so I'm sleeping at the time pulls are made and can't correct any resulting conflicts at once like last time.

There should be way to collaborate in pull requests...
If there is I would like to know.

For me main thing is that next time @quill18 does pulling at least one of these have no conflicts so we get this resolved. :)

**Comment by Ceddini** [comment]
@SanteriHetekivi I have the same problem with the time, since I live in Germany. And I'm currently learning for my drivers license so I don't have a lot of spare time. That being said, if you want to, you can pull from my PR and take my changes. If you write me back with a massage that you did it, i will close my PR. And if you wan't to be the guy for the languages, I would be happy to contribute my german knowledge :smile:

**Comment by SanteriHetekivi** [comment]
@Ceddini Okay I will merge it to mine.
I work full time and also go to school so I can't be very active. :(

**Comment by Ceddini** [comment]
**Caution: Wall of text incoming.**

@SanteriHetekivi I have a month of free time (I'm using this for my drivers license) and after that I'm beginning to study computer science. But my main problem is GitHub and Git in general. I don't really know how to use it correctly and fixing conflicts was quite a task for not knowing anything about it.
It would be great if @quill18 could do a very small tutorial on how to do it correctly. I think 4 or 5 minutes would be enough for that. :smile:.
I am sure that the community will be very active on translating things, because that seems like it's the easiest thing to do. But I think it is important to reduce the amount of PRs for translations because if conflicts occur then 20 people have to update their PRs and if we stuff all of them in 1 or 2 then it's pretty easy to update them. So I would suggest that a there is one person for each language so that no double entries occur and those people should be connected into a translation team to minimize the PRs, but that is not very important now. First comes the functionality, then the translations (except english. English is important :smiley:)

**Comment by SanteriHetekivi** [comment]
@Ceddini I'm just starting my last half year of Bachelor of Engineering.
I work and have been working been working 8 or more hours per day for last two years in programming, before then in any job I can land and of course in army I worked with computers in Reconnaissance Battery.
I'm working on web applications server sides and on mobile platforms currently.

I mostly program 8 hours for work and then almost another 8 for school, must keep perfect 5/5 going. ;D 
So I have very little interest to program on my limited free time, but I can keep Finnish translation coming before someone else wants to take over. :)

I was just testing the translation engine when I noticed that power generator issue.

**Comment by SanteriHetekivi** [comment]
Quill merged my PR #169 so I think this can be closed. :)

**Comment by SanteriHetekivi** [comment]
All but #236 are closed or merged and #236 contains conflicts.

**Comment by SanteriHetekivi** [comment]
Now all are closed or merged.
