### ISSUE TITLE
[Bug] Missing a ton of localizations

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#301]
Here's a list of things that I've found so far that aren't localized: Tile Inspector, Selection Panel, all of the Dialog Boxes,

**Comment by kd7uiy** [comment]
We should have a better default localization. Also, we should probably fall back to another language if one can't be found (English?).

**Comment by WardBenjamin** [comment]
Currently we do fall back to en_US for localizations.

**Comment by UnknownSoldier1** [comment]
What exactly do you mean with tile inspector? The thing on the bottom right? If so, I didn't localize it because I thought it would be a development only feature and it wouldn't make sense to localize something the user won't see. Then the selection panel isn't entirely localized due to missing features. And the dialog boxes should be localized, suprised that they aren't...

**Comment by WardBenjamin** [comment]
Also, it looks like *some* of the localizations are present for the Selection Panel, but not all, probably because we're falling back to en_US for most of the selections

**Comment by WardBenjamin** [comment]
@UnknownSoldier1 Ah, fair enough. I can work on localizing the dialog boxes after I open a pull request to add the introduction dialog.

**Comment by vogonistic** [comment]
Can we generate a list of missing localizations for en_US?

**Comment by mikejbrown** [comment]
Closing. If anyone finds a new missing en_US localization they can open a new issue now.
