### ISSUE TITLE
Disallow commented out code?

### ISSUE THREAD

**Issue by Mizipzor** [TeamPorcupine/ProjectPorcupine#440]
I'm not talking about documentation comments like these:

```
// this is an int
int i;
```

Rather, actual code that has been "removed" by being placed in a comment block. Like this:

```
//if (x > 0)
//    Do(x);
```

I'm seeing this in too many pull requests and would like to see a rule against it added to the contribution guidelines. This is one reason why Git is used, so you can go back and see what the code did before. It does nothing but add to clutter. If you use this trick to keep code around in case you want to go back to it (or something), I'm here and willing to teach you some proper Git. :)

Do we vote? Do a thumbs up or down on this post.

**Comment by bjubes** [comment]
I think we should disallow this if the code is no longer needed and the feature is mostly complete. However I don't think we should deny PR due to small comments like this, only when it adds lots of clutter.

**Comment by Mizipzor** [comment]
My argument is that they _always_ adds to clutter and never adds to readability. :)

**Comment by Grenkin1988** [comment]
@Mizipzor Strongly agree. Commented out code should not be in repository.

**Comment by vogonistic** [comment]
Yeah, commented out code should go unless there is a very compelling and documented reason for it to stay. The biggest exception would if an API has some code showing how it can be used.

**Comment by Randshot** [comment]
I also agree, except for logging calls.
I think that they should be commented out instead of entirely removed.
Just my opinion though ;)

**Comment by Mizipzor** [comment]
@Randshot instead of commenting out, how about logging to the verbose level?

**Comment by Randshot** [comment]
That's ok too :)

**Comment by vogonistic** [comment]
@Randshot @Mizipzor The problem with these kinds of logs is that you only want them when debugging one particular feature, like `job queue` or `pathfinder`. If we make all those logs Verbose, then you'll have to turn on verbose logging everywhere which would probably drown out your logs. It's better to keep commented out logs than turning everything verbose, but I'm not really happy with those either.

I often use something like this:
```cs
const traceLogThisModule = false;
function trace(params object[] things) {
    if (traceLogging) {
        // Debug.Log or Logger.Info or something here
    }
}
```

I haven't done it in C#, but I've done similar things in other languages. The compiler should be smart enough to optimize the calls away when turned off, but it allows you to turn on logging for just one particular subsystem when working on it and then turn it off so that nobody is bothered.

These kind of calls you don't even have to comment out and they'll most likely have some value to the next person testing your system.

There are probably smarter ways and some clever frameworks for this, but usually you don't need more than this.

**Comment by Randshot** [comment]
@vogonistic That's why I initially said that logging calls should be allowed to be commented out.
By I also understand that some don't like this either. In C++ I often used logging libraries which handled these kind of problems.

**Comment by vogonistic** [comment]
@Randshot Yeah, until we do something better. I'm ok with letting commented out logs calls be committed.

**Comment by ttyz** [comment]
It might be a good thing to add to "Best practices" section in CONTRIBUTING.md something like: "try to avoid committing commented code"

**Comment by Mizipzor** [comment]
@vogonistic I'm working on a channel system for logging thats intended to solve that. It's meant to filter message per component, like path finding.

If we allow commented out logging lines there is a strong consensus here. And not a single thumbs down on the initial post. This project is evolving extremely rapidly, I don't know how long these discussions should remain open. 24 hours?

**Comment by fre-ber** [comment]
Since spamming Debug.Log lags down Unity yo the point of crashing, putting all these testing log messages into "Verbose", or even "Debug" would group them all together. When debugging a specific feature, only the log messages for that particular feature is interesting, not the debug messages of the entire game and crashing Unity...

Even though I often keep commented out code, I think that for PRs, it might be a good thing to clean them out, except if they are pure debug log messages.  The channel thing might be the best solution if the channel identification part is easy to use.

**Comment by Mizipzor** [comment]
@fre-ber That was indeed the intended usage. You log to **info** as you develop so you see them all, but once youre done and about to push you replace it all with **verbose**.

**Comment by fre-ber** [comment]
@Mizipzor Yes, but if some poor sod accidentally sets the log level to **verbose**, Unity will die. Maybe, intead of switching these messages to **verbose** before push, one could switch them to **none** or something like that? Then they will still be in there to be easily re-activated but as long as they are at level **none**, they will never be displayed and they will never lag down the game. (Of course, if a log message is inside a very intense loop, even the call to the logger might cause a significant perfomance hit, but then I guess one could remove it completely before pushing)

**Comment by Mizipzor** [comment]
@fre-ber Hm, no I'm gonna have to respectfully disagree. I dont think anyone could _accidentally_ change the log level and then wonder why Unity slows to a crawl with log spam. 

Also, though I havent tested this, but I think that the most expensive part, by far, about logging is rendering that log view. If you would run the game outside Unity, or even with the log window invisible it wouldnt be nearly as severe.

**Comment by fre-ber** [comment]
@Mizipzor Well, what is the point of having a log level that can't be used?

Sure, this might not affect the game outside of Unity, but as it is now, all these spamming log messages has the potential to make it almost impossible to develop and test things.

**Comment by Mizipzor** [comment]
@fre-ber I'm working on a channel system for the logs where youre meant to be able to turn on or off certain systems, like path finding. Regardless, we're going rather off topic, create an issue if you want to be certain that this is addressed, or wait for the channel thing.

**Comment by fre-ber** [comment]
Ah, sorry, I will stop talking about that now, ;-) I think that we mostly agree anyway - the channel based system will solve the issue.

**Comment by sboigelot** [comment]
As @fre-ber said, we all agreed on this issue, we can probably close it.
