### ISSUE TITLE
StyleCop restrictions

### ISSUE THREAD

**Issue by Grenkin1988** [TeamPorcupine/ProjectPorcupine#485]
Some one please remove mandatory ```this.``` for local calls. This is really annoying.

**Comment by Mizipzor** [comment]
On it. Can we assign issues yet?

**Comment by Grenkin1988** [comment]
@Mizipzor You mean resolve issue by commit?

**Comment by Mizipzor** [comment]
No, I mean there is an **Assignees** field to the right, I would like to be listed there. :)

**Comment by Grenkin1988** [comment]
I think the same as labels. Only those who has merge rights

**Comment by Mizipzor** [comment]
Indeed, I wasnt asking you rather one of the gate keepers. Sorry I was unclear. :) The issue will be fixed regardless.

**Comment by Grenkin1988** [comment]
Also why 
SA-1400 (Validates that an access modifier is declared for an element.) and SA 1401 (Validates that a field is declared with private access.) are disabled?

**Comment by Mizipzor** [comment]
Pull request is up.

Regarding SA1401, we do use a lot of public fields. The norm is to, in that case, use and auto property instead. But it seems @quill18 disagrees with that. :)

**Comment by Grenkin1988** [comment]
@Mizipzor @quill18 And what about SA-1400 (Validates that an access modifier is declared for an element.)?
This is such a problem to write down `private`?

**Comment by quill18** [comment]
@Mizipzor No, I think it's fine to replace public fields with properties.  It's mostly that I'm trying to rush my typing a bit when I'm doing a tutorial.

I do think that forcing protected fields to be properties is a bit anal on the part of StyleCop's defaults, but I can't say that it's *wrong*.

I do see the clarity advantage from enforcing `this` everywhere, but it seems to be relatively minimal and I'm okay with removing that rule, especially since non-StyleCop people are unlikely to use it and that's just going to lead to a lot of annoying messages for those of us who do. (Since discovering StyleCop, I've become a fan).

I'd probably leave in the flag for adding `private` to fields. It's not going to puke a bunch of formatting errors in the middle of a function you're trying to debug, and it probably would be a fine idea to add `private` to fields -- though I wouldn't reject PRs for not having that, nor make it an explicit CONTRIBUTING guideline.

**Comment by Mizipzor** [comment]
@quill18 
> Since discovering StyleCop, I've become a fan

Yyeess, join the dark side. :)

On a more serious note, the rules you mention are still open for debate. One nice aspect of StyleCop is that you either turn the rule on or of. And the enabled rules leaves no room for interpretation.
