### ISSUE TITLE
StyleCop SA1512: A single-line comment must not be followed by a blank line.

### ISSUE THREAD

**Issue by fre-ber** [TeamPorcupine/ProjectPorcupine#519]
I do not see the benefit of this rule and vote for disabling it. In many places we have TODO sections similar to this:
```
    // TODO: Add thingymabob

    // TODO: Make thingymabob spin counter-clockwise

```
I think that the line separating these comments is useful, but this StyleCop rule disallows this. What do you think?

**Comment by fre-ber** [comment]
Oh, actually I was wrong, that use of comments is still allowed. What isn't is a blank line after the comment and the collowing code, like this:

```
    Character alice = new Character();
    Character Bob = new Character();

    /// TODO: Make Alice talk to Bob

    if (alice.TalksTo (bob)
    {
        ...
```

I still vote for disabling the rule.

**Comment by Mizipzor** [comment]
The reason for this is consistency. If youre commenting a certain line the comment should be directly above that line and nowhere else. The rule that disallows this serves the same purpose.

```
string name; // cant describe name here
```

But what if you aren't describing a certain line? You've found a such a use
case. And I actually thought it was four `////` rather than three `///`, but this type of comment is exempt from many of the StyleCop comment rules. And I think this type of comment **has to have** and empty line below it.

There's a clear benefit of using of both. I vote for that the rule stays. And maybe instead defining the different ways of commenting in the contribution guidelines (at the bottom).

**Comment by fre-ber** [comment]
LOL, that /// was actually a typo, however, I can accept the need to use //// instead of // for these comments, but I think that this means that we have a lot of things to change and, as you say, we need to update the guidlines.

**Comment by kd7uiy** [comment]
It seems all of the code meets the guidelines now, so should this still be opened?

**Comment by vogonistic** [comment]
I'm closing it for inactivity if nothing else.
