### ISSUE TITLE
Funiture params

### ISSUE THREAD

**Issue by sboigelot** [TeamPorcupine/ProjectPorcupine#532]
Furniture params can only be float.
We should expand this to allow at least string as a valid param.

**Comment by fre-ber** [comment]
A simple way could be to add another dictionary, stringParameters, but as came up in the atmosphere discussion, we might need a more flexible parameter system that would allow us to specify things like a string AND a float together in a single parameter.

Turning all parameters into strings and have them encoded in json or something would be a possibility, but a possibility that I don't particularily like.

**Comment by FilippoLeon** [comment]
what about:
`<Param name="oxygen" type="float">55</Param>`

store everything as string inside a structure:
`
Dictionary<string, structure_similar_to_tuple>
`
where the key is a string (name) and the value is a "tuple" value + type
and convert using a function:
```
GetParam<T>(string name) {
   read type and value
   do appropriate cast
   check compatibilty with T
   complain or return value
}
```

**Comment by koosemose** [comment]
I have an additional idea that may be useful for some furnitures (such as O2 Generator), that will however require a bit more complexity than @FilippoLeon's current WIP PR allows. Basically ParameterLists (or ParameterGroups) allowing multiple parameters to be grouped and accessed as such, and a very important part is for them to be able to be stored similarly (I'm thinking subclassing would be the most reasonable way to do this). An example of what the XML would look like from what I'm thinking for O2 Generators:
```
        <Params>
            <Param name="gas_limit" value="0.2" />
            <Param name="gas_per_second" value="0.16" />
            <ParamList name="gas_gen"> 
                <ParamList name="O2">
                    <Param name="gas_limit" value="0.2">
                </ParamList>
                <ParamList name="N2">
                    <Param name="gas_limit" value="0.8">
                </ParamList>
            </ParamList>
                        
        </Params>
```

I'm still working out how exactly this would be accessed from the code side (mostly because I don't think LUA can handle some of the C# I'd want to use in my optimal case), but it would be something along the lines of `furnParameters.GetValue("gas_gen").GetValue("O2").GetValue("gas_limit").AsFloat()`.

I'd prefer to implement it with an indexer (access as `furnParameters["gas_gen"]["O2"]["gas_limit"].AsFloat()`) but I doubt MoonSharp handles that well or at all.

**Comment by FilippoLeon** [comment]
What about implementing a type list or dictionary which will be read into a custom class that mimics  the standard list behaviour?

Would be
'''
< Param type=list name=gas>
< entry key=n2>0.2<\>
<Entry ...>
'''.

**Comment by sboigelot** [comment]
I don't know much about lua, but isn't it dynamically type?
Coudn't we just have the type of Param be object in c# ?
Then we don't have to change anything else, we store object instead of float.

**Comment by koosemose** [comment]
I'm not sure that that's functionally different from my example, unless it wouldn't be able to nest, and while it could mimic my versions behavior without it that was also an extremely simplified example, if for example I wanted each gas to also have an individual flow rate. Also your version isn't as self-documenting as my version (as you showed it anyways), if it weren't conveying the same information as mine was it wouldn't be clear what 0.2 is.

I'm pretty confident that I can implement it in a fairly simple way (looking at moonSharp docs, it looks like it has a way to do indexers), that should also be pretty powerful. I just don't want to stomp all over your work.

**Comment by koosemose** [comment]
The problem of storing it as an object is it would need to be cast all the time.

**Comment by FilippoLeon** [comment]
Go ahead and stomp. 

Maybe ParamDictionary would be more suitable?

**Comment by koosemose** [comment]
Maybe. ParamDictionary fits on the code side, since that's what it will mimic (and basically be underneath), but seems weird on the XML side. Whereas ParamList and ParamGroup fit on the XML side, and seem kind of weird on the code side.

I'll see what I can whip up and put up a WIP PR.

**Comment by fre-ber** [comment]
I think that the solution @koosemose suggested will be good. However, when this is implemented, please consider making it general enough so that we can plug the same system into anything that might need parameters/attributes such as Furniture, Character, Inventory, etc without the need to duplicate the code.

**Comment by FilippoLeon** [comment]
What if every class inherits from a master class which has Params and Actions?

**Comment by fre-ber** [comment]
Or the parameters are all stored in an object that can be added to other classes:

```
public class Parameters
{
    * Dictionary of dictionaries or whatever representation to use for generic parameters.
    * Accessor methods/operators/properties
    * Load/Save methods
}
class Furniture
{
    protected Parameters parameters;
}
class Character
{
    protected Parameters parameters;
}    
```

**Comment by koosemose** [comment]
As it stands now it will just be an object, you create a variable of that type and use it. I've not quite finished moving reading the Xml over, but as it stands now (and the intent of further implementation) is that in the future, for anything that has a Params section, when you come to your Params, you will just pass the reader to the object (or perhaps a static method in the class), and it will return an object with everything stuffed in. Obviously, there are still a few imprecisions in it, as I finish working out the kinks.

**Comment by koosemose** [comment]
Just an update report on my progress: The actual Parameter class is implemented, and seems to work as I want. I'm just trying to implement the Xml reading now, which isn't going nearly so well as it seems to get stuck on an end element and either errors out (as expected), or if I try loop until it reads past it, it will just loop forever. Something doesn't work how I think it does, it would seem.

**Comment by FilippoLeon** [comment]
You can create a WIP PR and we can try to figure it out together, if you wish.

**Comment by Grenkin1988** [comment]
#604 Here is another one discussion related to furniture

**Comment by koosemose** [comment]
I just might do that once I get it back into a state where it doesn't just blow up in my face... or at least push it to my own repository so you can look at it there. It may well conflict with the current the most recent version of the code, and I'd rather not have to try to resolve conflicts with the code I've horribly butchered in the process of trying to get this to work.

**Comment by koosemose** [comment]
BOOYAH! I've got it. I had to make a few decisions I'm less than happy with (for example, Param and ParamList are both Param, due to some oddities I couldn't straighten out with subReader, and ReadToSibling needing the tag name). I now have nesting Parameters (that can be either floats or strings, or technically anything that can convert to a float or string), it's properly accessible from Lua (I've converted all Lua functions currently in my version over to it), and should be usable with any class that needs Parameters, just pass your reader to a Parameter.ReadXml, and it will return a Parameter object that contains all your parameters. It will take me a while longer to clean up the terrible mess I made trying to get the XmlReader to behave, then properly document things (or at least something approaching documentation), and then make sure it can actually merge with the current version without conflicts.

Though I have just realized I haven't tested saving with it yet... soo hopefully I coded that right the first time.

**Comment by Mizipzor** [comment]
@koosemose is there a pull request for that?

**Comment by koosemose** [comment]
Not yet, I still have to clean up the code (it is chock full of Logging which is unneeded, commented out code from testing, completely uncommented, and deeply conflicting with the current codebase.) Once that's done, I'll look into PRing it.

**Comment by koosemose** [comment]
And I finally have a PR up for this. I even tried to include a summary of how it's used... though for as long as I've been working on it straight, I'm not sure how coherent the summary actually is.

**Comment by koosemose** [comment]
This issue should probably be closed now, as Parameters can accept strings now

**Comment by Mizipzor** [comment]
@koosemose do you know who made the commit that fixed this? The norm is to write "Fixes #XXX" in the commit message. That would have auto-closed this when the commit is merged. Or isnt it merged yet?

**Comment by koosemose** [comment]
That would've been me. It didn't seem so much as a fix to me as an enhancement, so I didn't think of including Fixes at the time. Is it possible to go back and add Fixes #xxx to an already merged commit?

**Comment by Mizipzor** [comment]
@koosemose not possible Im afraid, we'll do it the manual way. :)
