### ISSUE TITLE
Player jobs and inventory

### ISSUE THREAD

**Issue by JosephBywater** [TeamPorcupine/ProjectPorcupine#60]
I was wondering if there was a way to see what jobs are queued up for the player to complete. If there isn't already, it would be useful to see what jobs they are working on and will work on in future. Also, it would be useful to see what a character is currently holding, resource wise.

**Comment by BeefEX** [comment]
Just as Debug thing that could be very useful. I will try to do that.

**Comment by NogginBops** [comment]
I think there is a need (other people have expressed the same concern) to replace the current job system. I need reason is one of the features you are suggesting, seeing future jobs. Which would not be possible with the current codebase. I think it would be wise to wait on implementing this until the job system is fixed. As that would allow for a much easier implementation and more features.

**Comment by lameox** [comment]
I dont think the jobs can really be displayed in a good way. for one, the job currently only has a name and no real metadata associated with it. This could be displayed, but as soon as you want to display future jobs, it gets tricky, because all jobs are held in a global queue and you cant discern if your current character will do a given queued job or another character. Also there are jobs like the fetching of materials for a build job that never hit the job queue and are only ever added at the moment the jobsystem recognizes it is short some materials.

However the held resource should be easy.

**Comment by lameox** [comment]
@NogginBops i think that is the right idea. I might type up a proposal if i have the time today. Do you already have a concrete idea how to design the future job system i might expand on?

**Comment by NogginBops** [comment]
@lameox I have some ideas in mind. On my way home rn. Will open a issue on the matter soon. I wouldn't mind working on it today. Think I might get the general workings done today.

**Comment by lameox** [comment]
This sounds good. I think in the same turn we should also update the movement system. I want something like MoveTo(Tile) and the move to become a separate job. this should make writing any future additions a lot simpler as we wont have to roll the same path checks and stuff everywhere. Also having moves become separate jobs will allow us to write a job system akin to Linq. I had syntax in mind like 

Character.MoveTo(stockpile).PickUp("Iron", 3).PickUp("Aluminum", 2).MoveTo(workbench).Craft("door").MoveTo(stockpile).Drop("door").QueueJob

I dont know if that would be feasible but i think if we generate the right extension methods, writing jobs should become really intuitive for programmers and modders alike. What do you thnk?

**Comment by NogginBops** [comment]
@lameox I like your thinking. I think this could be implemented well with some kind of job bundling system so that when a character looks for a job it gets a job bundle. Like a complete package of what needs to be done.

Concern is that then a character could be idle while a character has a really big job bundle to finish. Though with some smart design I think that that could be easily solved.

**Comment by lameox** [comment]
@NogginBops we should probably move the discussion to #63

**Comment by NogginBops** [comment]
@lamenox Yeah, I'm home now so I can start discussing the inner workings a bit better.

**Comment by JosephBywater** [comment]
I'll close this then, as it's moved to #63
