### ISSUE TITLE
Milestone 0.1: Git branch naming conventions (git-flow)

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#694]
We had a chat among the Gatekeepers (me, @WardBenjamin, @RodRitter and @Mizipzor) trying to figure out how to not break things when switching methods and avoid having to train all the new developers coming in that are interested in the project but doesn't have much git experience.

We came to the conclusion that it would avoid a lot effort if we keep the `master` branch as the Development branch. We'd go with `git-flow`, but if people use UI tools for it, they have to configure `master` as Development and `stable` as Master.

Branches:
- `master` for merged development against the next release
- `feature/*` for PRs targetting `master` and the next release
- `hotfix/*` for bugfixes in an already released version
- `release/*` for release specific branches, this is where the hotfixes go
- `stable` for the tagged releases and to get the latest stable version.

What does this mean? It means that development can continue as is today. We'll start managing things differently from our (Gatekeeper) side and we'd prefer that new PRs use the new `feature/` prefix, but that's it. 

The only really drawback is that people who use git flow needs to change the settings from the default and that `master` isn't as descriptive as `develop` when it comes to volatility.

Questions? Feedback?

**Comment by vircung** [comment]
Using git-flow is good point. But i think we can get out without changing names for ```develop``` and ```master``` branches. That's because at some point ```develop``` and ```master``` need to point out to one commit because there won't be any ```master```/```stable``` to merge into. Additionally project is at very early stage without any official release.

Also GitHub gives ability to [change target branch](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) for PR so every PR that targets wrong branch can be labeled/commented as invalid with proper description.

**Comment by vogonistic** [comment]
We like the official git flow branch names `develop` and `master`, but the reasoning for going with `master` and `stable` was this:

  1. Keeping `master` as is allows people not familiar with git flow to keep working without changing anything. _(Better to be inclusive to beginners when it is an option)_
  1. While the target branch can be changed after a PR is made, it involves more work for gatekeepers and as we merge more PRs and change the code base, it will cause a lot of merge conflicts that we'll have to help people with. _(It's more important to merge PR's than have discussions about naming conventions)_

**Comment by vircung** [comment]
Actually we don't need to have multiple ```hotfix/*``` and ```release/*``` branches. Only one of those will be needed. That's because any changes made in branches ```hotfix``` and ```release``` should be merged back to ```master``` and ```stable```. Therefore there will be only 2 continuous branches ```master``` and ```stable```  every other should be removed after merging.

**Comment by Randshot** [comment]
@vogonistic Should we set origin or upstream as remote? (I am guessing origin, but want to make sure.)

**Comment by vogonistic** [comment]
@Randshot That only affects you since we never get to see what you called it. You just have to know what it means. I call it `upstream` personally.

**Comment by Randshot** [comment]
For now, I am not seeing any other branches than master on this repository.

**Comment by vogonistic** [comment]
We don't need `stable` until we make the first release, so we haven't created it yet. `master` is what all work will be focused on for now.

**Comment by Randshot** [comment]
One question, what is the point of using git-flow, when you can't merge the other (feature, hotfix, etc...) branches into the master branch?
Because when I click 'finish feature', it asks me how I want to merge the feature branch into the master branch.

**Comment by vogonistic** [comment]
You should have the ability to publish the feature, which you then create a pull request from.

**Comment by vogonistic** [comment]
Which app do you use?

**Comment by Randshot** [comment]
SmartGit

**Comment by vogonistic** [comment]
Hmm, I don't see the ability to publish your features. Smartgit's implementation of git flow seems to be focused on a single repo and might not be compatible with the fork & pull request model.

For now, can you disable git flow and do the usual PR's while we discuss this?

**Comment by Randshot** [comment]
I will just use the command line version :)

**Comment by sboigelot** [comment]
Do we have a consensus on this topic?

**Comment by vogonistic** [comment]
I've come to change my mind on bits in this. 

Git flow is a tool to manage feature branches within one repository and it's essentially the one repo version of the pull request model. 

It doesn't matter what anyone calls their branches. The only thing that matter is how we manage a stable and development branch within the main repo. 

We will probably go with something like this for merging fixes and keeping track of releases, but it's more of an implementation detail for gatekeepers and quill. We should have the information available on the wiki, but we don't have anything stable, so I don't feel a lot of pressure there. 

I'll update this issue a bit later today to reflect this.

**Comment by sboigelot** [comment]
Closing this issue for now as it's not a discussion anymore.

@vogonistic whenever you wish to make change, don't hesitate. But this will probably be more a question for the 30th of september and we can just do it and explain it later in the wiki.

**Comment by mikejbrown** [comment]
Reviving this for v0.1. How is this. Suppose the sake of argument that the current release version is vX.Y.Z.

* master: development branch, accepting features for the next milestone (i.e. vX.(Y+1) or v(X+1).0)
* release/vX.Y: feature frozen release branch, accepting bug fixes which bump Z
* hotfix/*: _temporary_ branches based on the relevant release, accepting bug fixes only. Merged into release (bumping Z) and (if relevant) master, then deleted. Z is bumped and a new release tagged _every_ time a hotfix gets merged.
* stable: the most recent stable release, usually just points to release/vX.Y.Z, gets moved anytime a hotfix gets merged or a new release happens

We'll have to ask anyone doing a bug fix to _pretty please_ base the fix on the oldest branch that makes sense so we don't have to rebase or cherry-pick all the time.

**Comment by Geoffrotism** [comment]
as a newb question. why would you want to fix a bug using an older branch rather than based on the master? wouldnt that lead to a lot more bugs/conflicts as you fix code that calls other stuff that might have changed?

**Comment by bjubes** [comment]
@Geoffrotism  lets say we release a version of the game and there is a bug. then the newest branch takes on the work for the next version, lets say its iimplementing pirates. If i fix the bug in the pirates branch then its not available to users, since pirates is unfinished. If we were to ship a new release with the bug fix the user would then have some pirate stuff in the game, which was not intented for them yet. BUT if i made the fix in the old branch we could ship that to the user immediately. Then when pirates is finished we rebase the pirates branch off of the old branch (which has my fix) and thus the bug is fixed in both the version we shipped to fix the bug and the new pirate version.

Hopefully that makes some sense

**Comment by bjubes** [comment]
However, i dont think we need a stable/developement setup until we are actually creating binaries and distributing to real users. This won't be relevant until we are in an "alpha" stage for this project

**Comment by mikejbrown** [comment]
@Geoffrotism It's usually still possible to apply the fix in @bjubes pirate situation, it's just some extra work with [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick). Most people find merging easier to manage so the oldest first strategy is preferred. :D
@bjubes Surely you mean merge, not rebase. :wink: I thought the point of v0.1 was to make a proof of concept release. Binaries would be useful for that, no? We'll very clearly label it "proof of concept," not "alpha."

**Comment by bjubes** [comment]
If we're testing the whole workflow now that 0.1 is finished then yes we should have seperate branches. It wouldn't be nessicary but it would prepare us for a seamless transition into an alpha stage. It is also worth noting that gatekeepers can change the pr base branch so if a pr is targeted at master we can change it to stable or vise versa. 

Yes I meant merge

**Comment by mikejbrown** [comment]
Yeah, happy to test the workflow now while things can still change a bit without breaking much.

I also think we should be merging fixes into release/vX.Y until the next release, but then stop. I.e., we'll never need to maintain more than one stable version.

There could be some hassle down the line when there are a lot of modders out there, but by then we'll be using proper semantic versioning and feeding the modders some not-so-gentle deprecation warnings when things change. It's up to them to keep up to date with the API of a pre-alpha game!

**Comment by bjubes** [comment]
If we can get gatekeeper consensus to do this I'm all for it

**Comment by koosemose** [comment]
While splitting branches into a proper development/release style setup is good for proof of concept, I worry that it could be problematic for development at this stage, most particularly fixes going into release, and waiting until we merge development into release, at this stage in our development, a lot of our "bugs" are just things that aren't implemented yet, and/or things that can make developing a feature that relates to the bug difficult, and as early as we are in development it's not incredibly uncommon for parts of our codebase to change drastically so that a bugfix  to even a week old release may not merge properly with new development, and may require entirely different code.

**Comment by bjubes** [comment]
I agree that until we actually are shipping a product, having two branches just adds headache to maintainers wihtout any added benefit. Maybe we can compromise by having a stable branch that is just the untouched version of the preivous milestone, and a master where all the work actually happens. Thus we begin to slowly adopt gitflow without causing unneeded conflicts between stable patches vs developmental features.

**Comment by koosemose** [comment]
That seems reasonable (keeping in mind that most of my knowledge of git and github has been learned since becoming a gatekeeper), basically getting the structure in place for what we will want in the future but keeping the procedures more friendly to our current state of development. 

I think if @mikejbrown agrees to this we will have consensus, as I'm reasonably sure we three are the active gatekeepers, possibly with an optional word in from @vogonistic as he still keeps somewhat of an eye on the project as he can afford the time.

**Comment by mikejbrown** [comment]
So for v0.1 you suggest we have a release branch and master, putting all bugfixes directly on master. Alright. If you guys are happy, I would be happy to cherry-pick bugfixes from master onto the release (mainly I just want to practice cherry-picking :wink:), keeping in mind that it will be (a) on an irregular when-I-get-around-to-it basis and (b) anything involving a big merge conflict probably won't go in.

**Comment by bjubes** [comment]
we dont actually have to cherry pick bug fixes on to release because were not releasing anything yet. We will have to cherry pick later but for now the release branch just becomes as dead branch after each milestone until the next.

when we do finally release, we will need cherry picks or hotfix branches

**Comment by mikejbrown** [comment]
Closing since there seems to be a consensus.
