### ISSUE TITLE
 Airlock Size and Visual Representation.

### ISSUE THREAD

**Issue by longtomjr** [TeamPorcupine/ProjectPorcupine#735]
I am planning on making the airlock art. I feel like the way the airlock is represented in game is maybe not final. I just want to have a little discussion about this. Maybe have a 2 or 3 tile long Airlock, and have the character wait in between the two doors for a bit.

What do you guys think?

**Comment by GamerInspired** [comment]
I think it would be awesome if you were to be able to make your own airlocks and just designate that area as an airlock.

**Comment by koosemose** [comment]
Yeah, I much prefer the idea of the Airlock currently in game be an Airlock door, and being able to designate our own airlocks. Something roughly akin to Prison Architect, where to be considered a valid Airlock it requires certain conditions be met (2 airlock doors, an air pump, and some kind of vac-suit storage locker). It would allow the player some planning and choice of style, i.e. do they want a tiny airlock that can only let one person through at a time (and therefore cycles quicker) or have a giant one that can let tons of people through (but cycles slowly). And also, should we have upgradeable tech, it allows us to have each part individually upgradeable, rather than just a single monolithic airlock.

Though of course maybe it would be feasible to have both as an option, a good ol' fashion do it yerself, and a Quillcorp readimade Airlock 4000 Deluxe (with red stripe)

**Comment by longtomjr** [comment]
I really like the idea you have there @koosemose and @GamerInspired !

**Comment by GamerInspired** [comment]
@koosemose I really like the expanded explication you gave about having it "a good ol' fashion do it yerself" method and I agree having a "Quillcorp readimade Airlock 4000 Deluxe (with red stripe)" would also be a good idea, maybe as a early game solution.

**Comment by Sommerbo** [comment]
Currently regular doors leak oxygen, Airlock doors do not so we can already build airlocks. Just wasteful ones
