### ISSUE TITLE
Being in room index 0 (outer space) destroys sensible furniture?

### ISSUE THREAD

**Issue by frankitox16** [TeamPorcupine/ProjectPorcupine#770]
That's a feature i'd like to add, so if you actually remove a wall (or it gets removed) but you didn't take all things that dont "stick to the ground" (sort of) they will fly away and be destroyed (checking if room index is 0 may not be the most legit way, but is an approach).

**Comment by koosemose** [comment]
I'm not sure how much this actually adds to gameplay other than making events that may breach your hull very debilitating. Not to mention it is reasonable to assume (based off our few real world examples) that virtually everything is going to be built into the floor or otherwise secured because things being able to float around would be very dangerous (assuming gravity was lost)

**Comment by kd7uiy** [comment]
I believe you mean sensitive furniture? Destroying it outright might be a bad idea, but I could see having some repairs required.

Also, this probably shouldn't be dependent on being outside, but rather on the atmosphere around it.
