### ISSUE TITLE
Load/Save doesn't work

### ISSUE THREAD

**Issue by vogonistic** [TeamPorcupine/ProjectPorcupine#813]
There is an exception thrown when trying to write the xml for inventory so it doesn't write the file.

**Comment by mikejbrown** [comment]
The game _saves_. Here is the result of saving on a new game: https://gist.github.com/mikejbrown/4539f2730471fd106f124571c24f108d

It fails on load though. One thing I noticed is that Character names aren't saved. Doubt if this is the only problem though.

**Comment by mikejbrown** [comment]
Also it seems Furniture param names are empty strings, which probably doesn't play well with the Parameters implementation (need more tests!)...

**Comment by koosemose** [comment]
I reported this a while back in #372, but it kind of fell off the radar. It's caused by a character carrying inventory, and then when you save the inventory won't have a tile which it wants for the X and Y.

**Comment by koosemose** [comment]
@mikejbrown ... I think I know why it doesn't have a name... maybe... it has to do with how I handle the ReadXml. But in the save file, the first Param is actually treated just like Params is in the prototype, meaning it's completely ignored, I'm not sure how/if I could do it so that the first call just writes a params tag... perhaps have the initially called WriteXml write the Params tag, and descend to the next level.

**Comment by koosemose** [comment]
And it seems as though characters aren't loaded anymore, not certain if this is an issue with how they are saved or how they are loaded.

**Comment by TomMalbran** [comment]
I've been checking this issue, and as everyone says there are several issues together. 

1. The inventory can't be saved when a char is holing it
2. The param names aren't saved, and that is because the param groups don't have names in the prototype. That is easy to fix by reading the names from the reader instead of the subReader. The highest level param won't have any name, but that shouldn't be an issue
3. The character names aren't saved, and those are required by the Visual Path code, which breaks the load. Saving them fixes that.

I am running into an issue where after loading from a save and saving again, there are several parameters missing, and I am trying to find where the issue is.

**Comment by koosemose** [comment]
The param groups do have a name in the proto (at least the o2 gen does, while still having the issue) the only issue is that the top level parameter doesn't have a name (it is basically the equivalent of the params tag), there is already a PR fixing this, basically it makes the top level a params tag with no name.

I've also got a fix in on the character names. And working on the inventory saving thing.

Since they're all related to this bug I've had to have a go at all of them to get to the root problem.

**Comment by TomMalbran** [comment]
@koosemose Check this line of the save https://gist.github.com/mikejbrown/4539f2730471fd106f124571c24f108d#file-test-sav-L909
There is no name, when clearly there should be one, and it will cause issues when loading.

The problem is that when you are reading the parameters group name at https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Models/Parameter.cs#L99 you are not reading the attribute of the actual param tag, since you are already on the sub tree. You should use ```reader.GetAttribute("name")```. Everything seems to work fine, because when you are reading the key to create the sub param group you are reading it before going to the subtree. If you log the param names they are empty for all the levels.

**Comment by TomMalbran** [comment]
To fix the inventory problem, we might need to start saving the jobs, if not, the character would start holding an inventory and nothing to do with it. Or an alternative would be to save the inventory  at the character location on the floor, until we start saving the jobs.

**Comment by koosemose** [comment]
That's peculiar, perhaps I misunderstood ReadSubtree  saying it started on the node that was current before it was called. I'll include that in the fix real quick.

**Comment by koosemose** [comment]
As is the character will dump the inventory as soon as they get a job that doesn't require it, or just use it for the next job if it does, (assuming I'm reading through the code correctly), if that's the case then the worst case scenario is they get a different job, and dump the inventory anyways, or they get the same/similar job and just use the inventory there. It should have the same end effect as your solution (dumping the inventory), but not require changing once jobs are saved.

**Comment by TomMalbran** [comment]
I saw the documentation and it does say that it starts on the current node. But if you log the name attribute from the subtree is empty. I don't know why, so better to read it from the reader.

That is good. so we can just save the character inventory.

**Comment by koosemose** [comment]
I've mostly got character inventory saving, just one small hiccup, Inventories are usually only on the ground at the start of the game, and of course we want them to be held by characters, but currently everything, particularly in InventorySpriteController relies on getting the location to instantiate the game object from the tile...

**Comment by koosemose** [comment]
PR #832 Should fix this bug completely.
