### ISSUE TITLE
Doors have no room and hence no atmosphere

### ISSUE THREAD

**Issue by Raketfart** [TeamPorcupine/ProjectPorcupine#823]
I was working on the character animation again, specifically taking off his helmet when inside with enough air.
That made me realize that every time the charater was in a doorway, he would put on his helmet. Thats because the doorway isn't in a room, and then has no atmosphere. 
I think we need to fix this somehow to avoid the character from choking. Or maybe he would put on a spacesuit when having to cross a doorway.

**Comment by Dan54** [comment]
I guess if the room is `null`, then the character doesn't update their helmet sprite.

**Comment by Raketfart** [comment]
@Dan54 Sure, I can fix it that way. My need for a fix is only temporary anyway, since he should probably take off the spacesuit in an airlock.

But won't we end up with many systems ignoring doors, like a character will just not try to breathe while in a doorway. And then you could build entire branches of your base consisting of only doors? 

Not sure if it's just something we'll handle if it becomes a problem, but just wanted to hear peoples input on this.

**Comment by koosemose** [comment]
Haven't you heard the old legend? If you don't hold your breath while passing through a doorway Space Ghosts will steal your soul.

But yeah, this is an odd problem, atmosphere is by room, and since doors and walls enclose rooms, they are by definition not in a room, but yeah, it's a little weird since you can of course go through rooms, they're still not part of the room. Perhaps at some point doors can give some composite of the atmosphere's of the two adjacent rooms when open?

**Comment by sboigelot** [comment]
You could check the adjacents tiles.rooms of the tile under the door.

**Comment by Dan54** [comment]
or you could use `Tile.GetGasPressure` if and when #833 gets merged

**Comment by Raketfart** [comment]
@Dan54 Perfect!

**Comment by Dan54** [comment]
#833 is merged.

**Comment by Raketfart** [comment]
Nice, I just tested, and it works with my problem
