### ISSUE TITLE
Stockpile enhancements

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#983]
Okay, I noticed a few interesting things that I suspect need some work with stockpiling:

![capture](https://cloud.githubusercontent.com/assets/5951269/18034102/95d7c75a-6d02-11e6-94b5-6fef233658b0.PNG)

First of all, I think that manufactured goods, IE, steel, should be the highest priority in stockpiling. Lowest would be raw goods. The thing is, I barely see steel being stockpiled at all. That seems like an error...

**Comment by WardBenjamin** [comment]
We should also be able to specify what material/group of materials to stockpile, if we want to. That option should probably be off by default, or required when you create the stockpile.

Another possible option would be a "collect" order where you specify a zone of material to collect that gets stockpiled, instead of everything getting stockpiled.
